(() => {
'use strict';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v)), num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const CONFIG={
  api:'https://api.coingecko.com/api/v3', scanMs:60*60*1000, focusMs:30*60*1000, positionMs:60*1000,
  stable:new Set(['usdt','usdc','dai','fdusd','usde','usds','pyusd','tusd','usdd','frax','usdp','gusd']),
  posKey:'ebyt-da-v4-positions', closedKey:'ebyt-da-v4-closed', creditKey:'ebyt-da-v4-credits', usedKey:'ebyt-da-v4-credits-used',
  authKey:'ebyt-da-v4-auth', authEmailKey:'ebyt-da-v4-auth-email', adminEmail:'admin@ebytda.local', demoPass:'EBYTDA-ADMIN-2026'
};
const I18N={
 fr:{personal:'Espace personnel',logout:'Déconnexion',credits:'crédits'},
 en:{personal:'Personal space',logout:'Logout',credits:'credits'}
};
const state={
  lang:localStorage.getItem('ebyt-lang')||'fr', cur:localStorage.getItem('ebyt-cur')||'eur', view:'home',
  rows:[], ranked:[], market:{}, selected:null, chartDays:1, nextScan:null, scanTimer:null, countTimer:null, posTimer:null,
  positions:JSON.parse(localStorage.getItem(CONFIG.posKey)||'[]'), closed:JSON.parse(localStorage.getItem(CONFIG.closedKey)||'[]'),
  credits:Number(localStorage.getItem(CONFIG.creditKey)||10000), creditsUsed:Number(localStorage.getItem(CONFIG.usedKey)||0),
  auth:localStorage.getItem(CONFIG.authKey)==='1', authEmail:localStorage.getItem(CONFIG.authEmailKey)||'', chart:null, candleSeries:null
};
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2800)}
function pct(v,d=2){return Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(d)} %`:'—'}
function score(v){return Number(v||0).toFixed(2)}
function klass(v){return num(v)>=0?'pos':'neg'}
function money(v,cur=state.cur){if(!Number.isFinite(Number(v)))return '—';const digits=Math.abs(v)<1?6:Math.abs(v)<100?3:2;return new Intl.NumberFormat(state.lang==='fr'?'fr-FR':'en-US',{style:'currency',currency:cur.toUpperCase(),maximumFractionDigits:digits}).format(v)}
function compact(v,cur=state.cur){if(!Number.isFinite(Number(v)))return '—';return new Intl.NumberFormat(state.lang==='fr'?'fr-FR':'en-US',{style:'currency',currency:cur.toUpperCase(),notation:'compact',maximumFractionDigits:1}).format(v)}
function avatar(sym){const txt=(sym||'?').toUpperCase().slice(0,3);return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><rect width="100%" height="100%" rx="40" fill="#0e2230"/><text x="50%" y="54%" dominant-baseline="middle" text-anchor="middle" fill="#f3d77f" font-size="24" font-family="Arial" font-weight="700">${txt}</text></svg>`)}
function seed(s){let x=0;for(const c of s)x=(x*31+c.charCodeAt(0))%1009;return (x%1000)/1000}
function consumeCredits(n=1){state.credits=Math.max(0,state.credits-n);state.creditsUsed+=n;localStorage.setItem(CONFIG.creditKey,String(state.credits));localStorage.setItem(CONFIG.usedKey,String(state.creditsUsed));renderCredits()}
function renderCredits(){if($('#creditBalance'))$('#creditBalance').textContent=state.credits.toLocaleString(state.lang==='fr'?'fr-FR':'en-US');if($('#creditUsed'))$('#creditUsed').textContent=`${state.creditsUsed.toLocaleString()} ${state.lang==='fr'?'utilisé(s)':'used'} • scan = 1 crédit`}

function showHome(){state.view='home';$('#publicHome').classList.remove('hidden');$('#privateApp').classList.add('hidden');$('#publicNav').classList.remove('hidden');$('#privateNav').classList.add('hidden');$$('.private-only').forEach(x=>x.classList.add('hidden'));$('#personalSpaceBtn').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
async function showDashboard(){if(!state.auth){openAuth();return}state.view='private';$('#publicHome').classList.add('hidden');$('#privateApp').classList.remove('hidden');$('#publicNav').classList.add('hidden');$('#privateNav').classList.remove('hidden');$$('.private-only').forEach(x=>x.classList.remove('hidden'));$('#personalSpaceBtn').classList.add('hidden');renderCredits();if(!state.rows.length)await scan(false);else{renderAll();loadChart()}startPositionTimer();setTimeout(()=>document.getElementById('radar').scrollIntoView({block:'start'}),20)}
function openAuth(){$('#authModal').classList.add('open');$('#authModal').setAttribute('aria-hidden','false');$('#adminEmail').value=CONFIG.adminEmail;setTimeout(()=>$('#adminPass').focus(),80)}
function closeAuth(){$('#authModal').classList.remove('open');$('#authModal').setAttribute('aria-hidden','true')}
function login(){const email=$('#adminEmail').value.trim().toLowerCase(),pass=$('#adminPass').value;if(email!==CONFIG.adminEmail||pass!==CONFIG.demoPass){toast('Identifiants administrateur invalides.');return}state.auth=true;state.authEmail=email;localStorage.setItem(CONFIG.authKey,'1');localStorage.setItem(CONFIG.authEmailKey,email);closeAuth();toast('Espace personnel déverrouillé.');showDashboard()}
function logout(){state.auth=false;state.authEmail='';localStorage.removeItem(CONFIG.authKey);localStorage.removeItem(CONFIG.authEmailKey);clearTimeout(state.scanTimer);clearInterval(state.countTimer);clearInterval(state.posTimer);showHome();toast('Session fermée.')}

function marketStats(rows){const tr=rows.filter(r=>!CONFIG.stable.has(r.symbol)),breadth=tr.length?tr.filter(r=>num(r.price_change_percentage_24h)>=0).length/tr.length*100:50,btc=rows.find(r=>r.symbol==='btc')||tr[0],eth=rows.find(r=>r.symbol==='eth')||tr[1],b24=num(btc?.price_change_percentage_24h),e24=num(eth?.price_change_percentage_24h),avg7=tr.length?tr.reduce((a,r)=>a+num(r.price_change_percentage_7d_in_currency),0)/tr.length:0,vol=tr.length?tr.reduce((a,r)=>a+Math.abs(num(r.price_change_percentage_24h)),0)/tr.length:0;let label='RANGE / MIXTE',base=60;if(breadth>62&&b24>1){label='RISK-ON';base=80}else if(breadth<38&&b24<-1){label='RISK-OFF';base=42}else if(Math.abs(b24)<.8&&Math.abs(avg7)<2){label='MARCHÉ PLAT';base=55}else if(e24>b24+1&&breadth>55){label='ROTATION ALTCOINS';base=77}if(vol>5)label+=' • VOLATIL';return{breadth,btc,vol,label,base,mode:vol>4.5?'focus':'normal'}}
function scoreAsset(r,m){const h1=num(r.price_change_percentage_1h_in_currency),d1=num(r.price_change_percentage_24h),d7=num(r.price_change_percentage_7d_in_currency),d30=num(r.price_change_percentage_30d_in_currency),vmc=num(r.total_volume)/num(r.market_cap,1),rank=num(r.market_cap_rank,100),ath=num(r.ath_change_percentage,-50),momentum=clamp(50+h1*8+d1*2.8+d7*.8),trend=clamp(50+d1*2+d7*1.2+d30*.28),volume=clamp(35+Math.log10(Math.max(vmc,.0001)*10000)*14),stability=clamp(84-Math.abs(d1)*3-Math.max(0,Math.abs(h1)-3)*4),tech=clamp(momentum*.36+trend*.34+volume*.2+stability*.1),capQuality=clamp(92-Math.log10(Math.max(rank,1))*21),liquidity=clamp(35+Math.log10(Math.max(num(r.total_volume),1))*5.3),recovery=clamp(90+ath*.4),fund=clamp(capQuality*.45+liquidity*.35+recovery*.2),quant=clamp(tech*.42+volume*.22+stability*.16+liquidity*.12+recovery*.08),rel=d1-num(m.btc?.price_change_percentage_24h),regime=clamp(m.base+rel*2.4+(m.breadth-50)*.25),accel=clamp(50+h1*10+(d1-h1*4)*3),fomo=clamp(accel*.36+volume*.20+tech*.18+quant*.12+regime*.14),riskPenalty=Math.max(0,Math.abs(d1)-9)*1.4+Math.max(0,Math.abs(h1)-5)*2;let ai=clamp(tech*.24+quant*.20+fund*.18+regime*.20+fomo*.18-riskPenalty+(seed(r.id)-.5)*1.2);let status='neutral',label=state.lang==='fr'?'NEUTRE':'NEUTRAL';if(ai>=82&&fomo>=78&&regime>=56){status='order';label=state.lang==='fr'?'ORDRE CONSEILLÉ':'ENTRY ADVISED'}else if(ai>=74&&fomo>=68){status='preorder';label=state.lang==='fr'?'PRÉ-ORDRE':'PRE-ORDER'}else if(ai>=64){status='watch';label=state.lang==='fr'?'À SURVEILLER':'WATCH'}const band=clamp(2.2+Math.abs(d1)*.22+Math.abs(h1)*.38,2,8),p=num(r.current_price),entryLow=p*(1-band*.0017),entryHigh=p*(1+band*.0010),stop=p*(1-(3+band*.45)/100),tp1=p*(1+(3.2+band*.55)/100),tp2=p*(1+(6.5+band*.95)/100),gains=[(tp1/p-1)*100,(tp2/p-1)*100,(tp2/p-1)*100+Math.max(2.2,d7*.12+2.2)],reasons=[];if(momentum>72)reasons.push('momentum en accélération');if(volume>68)reasons.push('volume/liquidité solides');if(quant>75)reasons.push('score Quant robuste');if(regime>70)reasons.push('régime favorable');if(rel>1.5)reasons.push('surperformance face au BTC');if(stability<45)reasons.push('volatilité élevée à contrôler');if(!reasons.length)reasons.push('configuration encore partielle');return{...r,tech,quant,fund,regime,fomo,ai,status,label,entryLow,entryHigh,stop,tp1,tp2,gains,reason:reasons.join(' • ')}}
function demoData(){const base=[['bitcoin','btc','Bitcoin'],['ethereum','eth','Ethereum'],['tether','usdt','Tether'],['binancecoin','bnb','BNB'],['solana','sol','Solana'],['usd-coin','usdc','USDC'],['ripple','xrp','XRP'],['dogecoin','doge','Dogecoin'],['cardano','ada','Cardano'],['avalanche-2','avax','Avalanche'],['chainlink','link','Chainlink'],['polkadot','dot','Polkadot'],['tron','trx','TRON'],['matic-network','pol','POL'],['litecoin','ltc','Litecoin'],['uniswap','uni','Uniswap'],['internet-computer','icp','Internet Computer'],['near','near','NEAR'],['aptos','apt','Aptos'],['arbitrum','arb','Arbitrum'],['optimism','op','Optimism'],['render-token','render','Render'],['sui','sui','Sui'],['aave','aave','Aave'],['cosmos','atom','Cosmos'],['stellar','xlm','Stellar'],['filecoin','fil','Filecoin'],['injective-protocol','inj','Injective'],['the-graph','grt','The Graph'],['maker','mkr','Maker']];while(base.length<100){let i=base.length+1;base.push([`asset-${i}`,`c${i}`,`Crypto ${i}`])}return base.map((c,i)=>{const s=seed(c[0]),p=i<5?[65000,3500,1,600,150][i]:Math.max(.04,160/(i+1)*(.6+s)),h=(s-.5)*7,d=(seed(c[1]+'d')-.46)*15,w=(seed(c[1]+'w')-.44)*30,m=(seed(c[1]+'m')-.45)*55;return{id:c[0],symbol:c[1],name:c[2],image:'',current_price:p,market_cap_rank:i+1,market_cap:p*(1e9/(i+1)),total_volume:p*(5e7/(i+1))*(1+s*2),price_change_percentage_1h_in_currency:h,price_change_percentage_24h:d,price_change_percentage_7d_in_currency:w,price_change_percentage_30d_in_currency:m,ath_change_percentage:-10-(1-s)*72}})}
async function fetchMarket(){const url=`${CONFIG.api}/coins/markets?vs_currency=${state.cur}&order=market_cap_desc&per_page=100&page=1&sparkline=false&price_change_percentage=1h,24h,7d,30d`;const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(r.status);const j=await r.json();if(!Array.isArray(j)||j.length<20)throw new Error('bad data');return j}
async function scan(manual=false){if(state.view!=='private')return;$('#refreshBtn').classList.add('spin');let raw,live=true;try{raw=await fetchMarket()}catch(e){raw=demoData();live=false;toast('API indisponible : données de démonstration actives.')}if(live)consumeCredits(1);const m=marketStats(raw);state.market=m;state.rows=raw.map(r=>scoreAsset(r,m)).sort((a,b)=>num(a.market_cap_rank)-num(b.market_cap_rank));state.ranked=state.rows.filter(r=>!CONFIG.stable.has(r.symbol)).sort((a,b)=>b.ai-a.ai);state.selected=state.rows.find(r=>r.id===state.selected?.id)||state.ranked[0];scheduleScan();renderAll();await loadChart();$('#refreshBtn').classList.remove('spin');if(manual)toast('Analyse complète recalculée.')}
function scheduleScan(){clearTimeout(state.scanTimer);clearInterval(state.countTimer);const ms=state.market.mode==='focus'?CONFIG.focusMs:CONFIG.scanMs;state.nextScan=Date.now()+ms;state.scanTimer=setTimeout(()=>scan(false),ms);state.countTimer=setInterval(renderCountdown,1000);renderCountdown()}
function renderCountdown(){if(!state.nextScan)return;const sec=Math.max(0,Math.floor((state.nextScan-Date.now())/1000)),mm=Math.floor(sec/60),ss=sec%60;$('#countdown').textContent=`${mm}m ${String(ss).padStart(2,'0')}s`}
function eligible(a){return state.ranked.slice(0,10).some(x=>x.id===a?.id)}
function rankOf(a){const i=state.ranked.findIndex(x=>x.id===a?.id);return i>=0?i+1:null}
function renderAll(){const top=state.ranked[0],m=state.market;if(!top)return;$('#marketRegime').textContent=m.label;$('#heroImg').src=top.image||avatar(top.symbol);$('#heroName').textContent=`${top.name} (${top.symbol.toUpperCase()})`;$('#heroPrice').textContent=money(top.current_price);$('#hero24h').textContent=pct(top.price_change_percentage_24h);$('#hero24h').className=klass(top.price_change_percentage_24h);$('#heroScore').textContent=score(top.ai);$('#heroSignal').textContent=top.label;$('#heroReason').textContent=top.reason;$('#engineTech').textContent=score(top.tech);$('#engineQuant').textContent=score(top.quant);$('#engineFund').textContent=score(top.fund);$('#engineRegime').textContent=score(top.regime);$('#engineFomo').textContent=score(top.fomo);$('#kpiSync').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});renderCredits();renderTop3();renderCryptoGrid();renderTop10();renderSelected();renderUniverse();renderPositions();renderClosed();renderPositionKpis();renderCountdown();updateNotificationState()}
function advisoryFor(a,i){if(i===0)return a.status==='order'?['order','PASSAGE CONSEILLÉ']:[a.status,a.label];if(i===1)return['preorder','PRÉ-ORDRE'];return['watch','À SURVEILLER']}
function renderTop3(){$('#top3').innerHTML=state.ranked.slice(0,3).map((a,i)=>{const[cls,label]=advisoryFor(a,i);return`<article class="fcard ${cls}"><div class="fcard-head"><div class="asset"><img src="${a.image||avatar(a.symbol)}"><div><b>${a.name}</b><small>${a.symbol.toUpperCase()}</small></div></div><button class="rank-btn" data-pick="${a.id}">#${i+1}</button></div><div class="score-line"><div><small>FOMO</small><strong>${score(a.fomo)}</strong></div><span class="status-pill ${cls}">${label}</span></div><p>${a.reason}</p><div class="fmeta"><div><small>IA</small><b>${score(a.ai)}</b></div><div><small>QUANT</small><b>${score(a.quant)}</b></div><div><small>24 h</small><b class="${klass(a.price_change_percentage_24h)}">${pct(a.price_change_percentage_24h)}</b></div></div><button class="order-mini-btn" data-order="${a.id}">ORDRE • BROKER →</button></article>`}).join('');$$('[data-pick]',$('#top3')).forEach(b=>b.onclick=()=>selectAsset(b.dataset.pick,true));$$('[data-order]',$('#top3')).forEach(b=>b.onclick=e=>{e.stopPropagation();selectAsset(b.dataset.order,false);openOrder()})}
function renderCryptoGrid(){$('#cryptoGrid100').innerHTML=state.rows.slice(0,100).map(a=>{const cls=a.ai>=80?'hot':a.ai>=65?'mid':'low';return`<button class="crypto-tile ${cls}" data-gridpick="${a.id}"><b>#${a.market_cap_rank} ${a.symbol.toUpperCase()}</b><span>${a.name}</span><small>IA ${score(a.ai)} • ${pct(a.price_change_percentage_24h,1)}</small></button>`}).join('');$$('[data-gridpick]').forEach(b=>b.onclick=()=>selectAsset(b.dataset.gridpick,true))}
function renderTop10(){$('#top10Rows').innerHTML=state.ranked.slice(0,10).map((a,i)=>`<tr class="${state.selected?.id===a.id?'selected':''}" data-rowpick="${a.id}"><td><button class="table-rank" data-pick="${a.id}">#${i+1}</button></td><td><div class="asset"><img src="${a.image||avatar(a.symbol)}"><div><b>${a.name}</b><small>${a.symbol.toUpperCase()}</small></div></div></td><td>${money(a.current_price)}</td><td class="${klass(a.price_change_percentage_24h)}">${pct(a.price_change_percentage_24h)}</td><td><span class="score-chip">${score(a.tech)}</span></td><td><span class="score-chip">${score(a.quant)}</span></td><td><span class="score-chip">${score(a.fund)}</span></td><td><span class="score-chip">${score(a.regime)}</span></td><td><span class="score-chip ${a.fomo>=80?'high':''}">${score(a.fomo)}</span></td><td><span class="score-chip ${a.ai>=80?'high':''}">${score(a.ai)}</span></td><td><span class="status-pill ${a.status}">${a.label}</span></td><td><button class="order-mini-btn" data-order="${a.id}">ORDRE</button></td></tr>`).join('');$$('[data-pick]',$('#top10Rows')).forEach(b=>b.onclick=e=>{e.stopPropagation();selectAsset(b.dataset.pick,true)});$$('[data-rowpick]').forEach(r=>r.onclick=()=>selectAsset(r.dataset.rowpick,true));$$('[data-order]',$('#top10Rows')).forEach(b=>b.onclick=e=>{e.stopPropagation();selectAsset(b.dataset.order,false);openOrder()})}
function selectAsset(id,scroll=false){const a=state.rows.find(x=>x.id===id)||state.ranked.find(x=>x.id===id);if(!a)return;state.selected=a;renderSelected();renderTop10();loadChart();if(scroll)document.querySelector('.grid').scrollIntoView({behavior:'smooth',block:'start'})}
function trackStats(a){const p90=num(a.price_change_percentage_30d_in_currency)*2.4,posDays=clamp(48+seed(a.id+'p')*30),vol=clamp(Math.abs(num(a.price_change_percentage_24h))*.22+2.8,1,25),dd=-clamp(Math.abs(num(a.ath_change_percentage))*0.35,5,65),cont=clamp(22+seed(a.id+'c')*58);return{p90,posDays,vol,dd,cont}}
function renderSelected(){const a=state.selected;if(!a)return;const r=rankOf(a),ok=eligible(a),tr=trackStats(a);$('#chartImg').src=a.image||avatar(a.symbol);$('#chartName').textContent=a.name;$('#chartSymbol').textContent=a.symbol.toUpperCase();$('#chartPrice').textContent=money(a.current_price);$('#chartChange').textContent=pct(a.price_change_percentage_24h);$('#chartChange').className=`price-change ${klass(a.price_change_percentage_24h)}`;$('#chartRank').textContent=r?`TOP ${r}`:`Rang marché #${a.market_cap_rank||'—'}`;$('#chartEligibility').textContent=ok?`✓ TOP ${r} • ORDRE AUTORISÉ`:'GRAPHIQUE SEUL • HORS TOP 10';$('#chartEligibility').className=`eligibility ${ok?'yes':''}`;$('#selectedStatus').textContent=`${a.label} • ${r?`TOP ${r}`:`#${a.market_cap_rank||'—'}`}`;$('#selectedScore').textContent=score(a.ai);$('#selTech').textContent=score(a.tech);$('#selQuant').textContent=score(a.quant);$('#selFund').textContent=score(a.fund);$('#selRegime').textContent=score(a.regime);$('#selFomo').textContent=score(a.fomo);$('#entryZone').textContent=`${money(a.entryLow)} – ${money(a.entryHigh)}`;$('#stopLevel').textContent=money(a.stop);$('#tp1Level').textContent=money(a.tp1);$('#tp2Level').textContent=money(a.tp2);$('#selectedReason').textContent=a.reason;$('#gain1').textContent=pct(a.gains[0]);$('#gain2').textContent=pct(a.gains[1]);$('#gain3').textContent=pct(a.gains[2]);$('#openOrderBtn').disabled=!ok;$('#orderEligibilityNote').textContent=ok?`TOP ${r} : cliquez pour choisir le broker, l’horizon et enregistrer l’exécution réelle.`:'Actif hors TOP 10 : impossible d’ouvrir un ticket d’ordre.';$('#trkPerf').textContent=pct(tr.p90);$('#trkPos').textContent=`${tr.posDays.toFixed(2)} %`;$('#trkVol').textContent=`${tr.vol.toFixed(2)} %`;$('#trkDD').textContent=`${tr.dd.toFixed(2)} %`;$('#trkCont').textContent=`${tr.cont.toFixed(2)} %`;$('#trkScore').textContent=`${Math.round(a.ai)}/100`}
function renderUniverse(){const q=$('#search').value.trim().toLowerCase(),f=$('#statusFilter').value,list=state.rows.filter(a=>(!q||a.name.toLowerCase().includes(q)||a.symbol.toLowerCase().includes(q))&&(f==='all'||a.status===f));$('#cryptoRows').innerHTML=list.map(a=>`<tr data-chartpick="${a.id}"><td>${a.market_cap_rank||'—'}</td><td><div class="asset"><img src="${a.image||avatar(a.symbol)}"><div><b>${a.name}</b><small>${a.symbol.toUpperCase()} ${eligible(a)?'• TOP 10':''}</small></div></div></td><td>${money(a.current_price)}</td><td class="${klass(a.price_change_percentage_1h_in_currency)}">${pct(a.price_change_percentage_1h_in_currency)}</td><td class="${klass(a.price_change_percentage_24h)}">${pct(a.price_change_percentage_24h)}</td><td class="${klass(a.price_change_percentage_7d_in_currency)}">${pct(a.price_change_percentage_7d_in_currency)}</td><td>${compact(a.total_volume)}</td><td><span class="score-chip">${score(a.tech)}</span></td><td><span class="score-chip">${score(a.quant)}</span></td><td><span class="score-chip">${score(a.fund)}</span></td><td><span class="score-chip">${score(a.regime)}</span></td><td><span class="score-chip">${score(a.fomo)}</span></td><td><span class="score-chip ${a.ai>=80?'high':''}">${score(a.ai)}</span></td><td><span class="status-pill ${a.status}">${a.label}</span></td></tr>`).join('');$$('[data-chartpick]').forEach(r=>r.onclick=()=>selectAsset(r.dataset.chartpick,true))}
function ensureChart(){if(state.chart||!window.LightweightCharts)return;state.chart=LightweightCharts.createChart($('#chart'),{layout:{background:{type:'solid',color:'#071019'},textColor:'#8ea1af'},grid:{vertLines:{color:'#10202b'},horzLines:{color:'#10202b'}},rightPriceScale:{borderColor:'#1a2a37'},timeScale:{borderColor:'#1a2a37',timeVisible:true,secondsVisible:false},crosshair:{mode:LightweightCharts.CrosshairMode.Normal}});state.candleSeries=state.chart.addCandlestickSeries({upColor:'#34d399',downColor:'#fb7185',borderUpColor:'#34d399',borderDownColor:'#fb7185',wickUpColor:'#34d399',wickDownColor:'#fb7185'});new ResizeObserver(entries=>{for(const e of entries)state.chart.applyOptions({width:e.contentRect.width,height:e.contentRect.height})}).observe($('#chart'))}
function demoCandles(a,days){const count=days===1?48:days===7?84:days===30?100:120,end=Math.floor(Date.now()/1000),step=Math.floor(days*86400/count),out=[];let p=num(a.current_price,1)*(1-(seed(a.id+'c')-.4)*.08);for(let i=count-1;i>=0;i--){const s=(seed(a.id+i)-.5)*.025,o=p,c=o*(1+s),h=Math.max(o,c)*(1+Math.abs(s)*.5+.002),l=Math.min(o,c)*(1-Math.abs(s)*.5-.002);out.push({time:end-i*step,open:o,high:h,low:l,close:c});p=c}const factor=num(a.current_price,1)/out[out.length-1].close;return out.map(c=>({...c,open:c.open*factor,high:c.high*factor,low:c.low*factor,close:c.close*factor}))}
async function loadChart(){const a=state.selected;if(!a||state.view!=='private')return;ensureChart();if(!state.candleSeries){$('#chartStatus').textContent='Bibliothèque graphique indisponible';return}$('#chartStatus').textContent='Chargement des bougies…';let candles;try{const r=await fetch(`${CONFIG.api}/coins/${encodeURIComponent(a.id)}/ohlc?vs_currency=${state.cur}&days=${state.chartDays}`);if(!r.ok)throw new Error(r.status);const j=await r.json();candles=j.map(x=>({time:Math.floor(x[0]/1000),open:x[1],high:x[2],low:x[3],close:x[4]}));if(!candles.length)throw new Error('empty');$('#chartStatus').textContent='Bougies OHLC • CoinGecko'}catch(e){candles=demoCandles(a,state.chartDays);$('#chartStatus').textContent='Bougies de démonstration • OHLC API indisponible'}state.candleSeries.setData(candles);state.chart.timeScale().fitContent()}
function recommendedHorizonMinutes(a){const v=Math.abs(num(a.price_change_percentage_24h));if(a.fomo>=90||v>=10)return 240;if(a.fomo>=82||v>=6)return 720;if(a.ai>=78)return 1440;return 2880}
function horizonLabel(min){if(min<60)return`${min} min`;if(min<1440)return`${Math.round(min/60)} h`;return`${Math.round(min/1440)} j`}
function openOrder(){const a=state.selected;if(!state.auth){openAuth();return}if(!eligible(a)){toast('Ordre verrouillé : actif hors TOP 10.');return}const r=rankOf(a),auto=recommendedHorizonMinutes(a);$('#modalAsset').textContent=`${a.name} (${a.symbol.toUpperCase()})`;$('#modalRank').textContent=`TOP ${r}`;$('#capitalCurrency').textContent=state.cur.toUpperCase();$('#executionCurrency').textContent=state.cur.toUpperCase();$('#executionInput').value=num(a.current_price).toPrecision(8).replace(/0+$/,'').replace(/\.$/,'');$('#ticketAi').textContent=score(a.ai);$('#ticketFomo').textContent=score(a.fomo);$('#ticketStop').textContent=money(a.stop);$('#ticketTps').textContent=`${money(a.tp1)} / ${money(a.tp2)}`;$('#ticketHorizon').textContent=`${horizonLabel(auto)} (IA)`;$('#horizonSelect').value='auto';$('#manualCheck').checked=false;$('#confirmOrderBtn').disabled=true;$('#orderModal').classList.add('open');$('#orderModal').setAttribute('aria-hidden','false')}
function closeOrder(){$('#orderModal').classList.remove('open');$('#orderModal').setAttribute('aria-hidden','true')}
async function fetchBothPrice(id){try{const r=await fetch(`${CONFIG.api}/simple/price?ids=${encodeURIComponent(id)}&vs_currencies=eur,usd`);if(!r.ok)throw new Error();const j=await r.json();return j[id]||null}catch(e){return null}}
async function confirmOrder(){const a=state.selected;if(!eligible(a))return;const capital=num($('#capitalInput').value),entry=num($('#executionInput').value);if(capital<=0||entry<=0){toast('Capital ou prix invalide.');return}const both=await fetchBothPrice(a.id);let entryEur,entryUsd;if(state.cur==='eur'){entryEur=entry;entryUsd=both?.usd&&both?.eur?entry*(both.usd/both.eur):entry*1.1}else{entryUsd=entry;entryEur=both?.eur&&both?.usd?entry*(both.eur/both.usd):entry/1.1}const qty=capital/entry,side=$('#sideSelect').value,stopPct=Math.abs((a.stop/a.current_price-1)*100),tp1Pct=Math.abs((a.tp1/a.current_price-1)*100),tp2Pct=Math.abs((a.tp2/a.current_price-1)*100),rawH=$('#horizonSelect').value,horizonMinutes=rawH==='auto'?recommendedHorizonMinutes(a):Number(rawH),openedAt=new Date(),targetCloseAt=new Date(openedAt.getTime()+horizonMinutes*60000);const pos={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),assetId:a.id,symbol:a.symbol,name:a.name,image:a.image||'',rank:rankOf(a),broker:$('#brokerSelect').value,side,qty,openedAt:openedAt.toISOString(),targetCloseAt:targetCloseAt.toISOString(),horizonMinutes,exitWindowNotified:false,orderCurrency:state.cur,capitalOriginal:capital,entryEur,entryUsd,currentEur:both?.eur||entryEur,currentUsd:both?.usd||entryUsd,stopPct,tp1Pct,tp2Pct,ai:a.ai,fomo:a.fomo,maxPnlPct:0,minPnlPct:0,status:'open'};state.positions.unshift(pos);consumeCredits(1);persistPositions();closeOrder();renderPositions();renderPositionKpis();toast(`${a.symbol.toUpperCase()} : position ouverte dans EBYTDA.`);document.getElementById('positions').scrollIntoView({behavior:'smooth'})}
function persistPositions(){localStorage.setItem(CONFIG.posKey,JSON.stringify(state.positions))}
function persistClosed(){localStorage.setItem(CONFIG.closedKey,JSON.stringify(state.closed))}
function posCalc(p){const cur=state.cur==='eur'?num(p.currentEur):num(p.currentUsd),entry=state.cur==='eur'?num(p.entryEur):num(p.entryUsd),sgn=p.side==='short'?-1:1,pnlPct=entry?((cur-entry)/entry*100)*sgn:0,pnlMoney=p.qty*(cur-entry)*sgn,capital=p.qty*entry,target=new Date(p.targetCloseAt||p.openedAt).getTime(),opened=new Date(p.openedAt).getTime(),now=Date.now(),timeProgress=target>opened?clamp((now-opened)/(target-opened)*100,0,100):100,remaining=Math.max(0,target-now);return{cur,entry,pnlPct,pnlMoney,capital,progress:clamp((pnlPct/Math.max(p.tp1Pct,.01))*100,0,160),target,timeProgress,remaining,due:now>=target}}
function remainingLabel(ms){if(ms<=0)return'FENÊTRE ARRIVÉE';const mins=Math.ceil(ms/60000);if(mins<60)return`${mins} min`;if(mins<1440)return`${Math.floor(mins/60)} h ${mins%60} min`;return`${Math.floor(mins/1440)} j ${Math.floor((mins%1440)/60)} h`}
function renderPositions(){if(!state.positions.length){$('#positionsList').innerHTML='<div class="empty">Aucune position ouverte. Passez par le TOP 3 ou le TOP 10 pour créer un ticket.</div>';return}$('#positionsList').innerHTML=state.positions.map(p=>{const c=posCalc(p),cl=c.pnlMoney>=0?'profit':'loss';return`<article class="position-card ${cl}"><div class="position-top"><div class="position-title"><img src="${p.image||avatar(p.symbol)}"><div><b>${p.name} • ${p.symbol.toUpperCase()}</b><small>${p.side.toUpperCase()} • ${p.broker} • TOP ${p.rank}</small></div></div><div class="pmetric"><span>Entrée</span><b>${money(c.entry)}</b></div><div class="pmetric"><span>Actuel</span><b>${money(c.cur)}</b></div><div class="pmetric"><span>P&amp;L</span><b class="pnl-big ${klass(c.pnlMoney)}">${money(c.pnlMoney)}</b></div><div class="pmetric"><span>P&amp;L %</span><b class="${klass(c.pnlPct)}">${pct(c.pnlPct)}</b></div><button class="close-btn" data-closepos="${p.id}">CLÔTURER</button></div><div class="position-progress"><div class="progress-track"><div class="progress-bar" style="width:${Math.min(100,c.progress)}%"></div></div><div class="progress-label">Progression vers TP1 : ${c.progress.toFixed(0)} %</div></div><div class="perf-indexes"><div><span>MFE max</span><b class="pos">${pct(p.maxPnlPct||0)}</b></div><div><span>MAE min</span><b class="neg">${pct(p.minPnlPct||0)}</b></div><div><span>Horizon</span><b>${horizonLabel(p.horizonMinutes||0)}</b></div><div><span>Fenêtre sortie</span><b class="${c.due?'neg':''}">${remainingLabel(c.remaining)}</b></div></div><div class="position-meta"><span>Ouverte ${new Date(p.openedAt).toLocaleString()}</span><span>Capital suivi ${money(c.capital)}</span><span>TP1 +${p.tp1Pct.toFixed(2)} %</span><span>TP2 +${p.tp2Pct.toFixed(2)} %</span><span>Stop -${p.stopPct.toFixed(2)} %</span><span class="position-window ${c.due?'due':''}">${c.due?'⚠ FENÊTRE DE SORTIE':'⏱ '+remainingLabel(c.remaining)}</span></div></article>`}).join('');$$('[data-closepos]').forEach(b=>b.onclick=()=>closePosition(b.dataset.closepos))}
function renderPositionKpis(){const cs=state.positions.map(posCalc),capital=cs.reduce((a,c)=>a+c.capital,0),pnl=cs.reduce((a,c)=>a+c.pnlMoney,0),pctTot=capital?pnl/capital*100:0;$('#kpiOpen').textContent=state.positions.length;$('#kpiCapital').textContent=capital?`Capital suivi ${money(capital)}`:'—';$('#kpiPnl').textContent=money(pnl);$('#kpiPnl').className=`kpi-value ${klass(pnl)}`;$('#kpiPnlPct').textContent=pct(pctTot);$('#kpiPnlPct').className=`kpi-sub ${klass(pctTot)}`}
function closePosition(id){const i=state.positions.findIndex(p=>p.id===id);if(i<0)return;const p=state.positions[i],c=posCalc(p);if(!confirm(`Clôturer ${p.symbol.toUpperCase()} avec le P&L actuel ${money(c.pnlMoney)} ?`))return;state.positions.splice(i,1);state.closed.unshift({...p,status:'closed',closedAt:new Date().toISOString(),exitEur:p.currentEur,exitUsd:p.currentUsd});state.closed=state.closed.slice(0,200);persistPositions();persistClosed();renderPositions();renderClosed();renderPositionKpis()}
function renderClosed(){if(!state.closed.length){$('#closedList').innerHTML='<div class="empty">Aucune position clôturée enregistrée.</div>';return}$('#closedList').innerHTML=state.closed.map(p=>{const entry=state.cur==='eur'?num(p.entryEur):num(p.entryUsd),exit=state.cur==='eur'?num(p.exitEur):num(p.exitUsd),sgn=p.side==='short'?-1:1,pnl=p.qty*(exit-entry)*sgn,pp=entry?((exit-entry)/entry*100)*sgn:0;return`<div class="closed-row"><span>${new Date(p.closedAt).toLocaleString()}</span><b>${p.name} (${p.symbol.toUpperCase()}) • ${p.broker}</b><span>${p.side.toUpperCase()}</span><b class="${klass(pnl)}">${money(pnl)}</b><b class="${klass(pp)}">${pct(pp)}</b></div>`}).join('')}
async function refreshPositionPrices(manual=false){if(!state.positions.length){if(manual)toast('Aucune position ouverte.');return}const ids=[...new Set(state.positions.map(p=>p.assetId))];try{const r=await fetch(`${CONFIG.api}/simple/price?ids=${ids.map(encodeURIComponent).join(',')}&vs_currencies=eur,usd`);if(!r.ok)throw new Error();const j=await r.json();state.positions=state.positions.map(p=>{const updated={...p,currentEur:num(j[p.assetId]?.eur,p.currentEur),currentUsd:num(j[p.assetId]?.usd,p.currentUsd),lastPriceAt:new Date().toISOString()};const c=posCalc(updated);updated.maxPnlPct=Math.max(num(p.maxPnlPct,0),c.pnlPct);updated.minPnlPct=Math.min(num(p.minPnlPct,0),c.pnlPct);return updated});persistPositions();checkExitWindows();renderPositions();renderPositionKpis();if(manual)toast('Prix des positions actualisés.')}catch(e){if(manual)toast('Actualisation des prix indisponible.')}}
function startPositionTimer(){clearInterval(state.posTimer);state.posTimer=setInterval(()=>{refreshPositionPrices(false);checkExitWindows()},CONFIG.positionMs);refreshPositionPrices(false);checkExitWindows()}
async function requestNotifications(){if(!('Notification'in window)){toast('Notifications navigateur non prises en charge.');return}if(Notification.permission==='granted'){updateNotificationState();toast('Notifications déjà actives.');return}const perm=await Notification.requestPermission();updateNotificationState();toast(perm==='granted'?'Notifications activées.':'Notifications non autorisées.')}
function updateNotificationState(){const e=$('#notifyState');if(!e)return;const p=('Notification'in window)?Notification.permission:'unsupported';e.textContent=p==='granted'?'ON':p==='denied'?'BLOQUÉ':'OFF';e.className=`kpi-value compact-value ${p==='granted'?'pos':''}`}
function fireExitNotification(p){const msg=`${p.symbol.toUpperCase()} : la fenêtre de fermeture estimée est arrivée.`;toast('⚠ '+msg);if('Notification'in window&&Notification.permission==='granted'){try{new Notification('EBYTDA • Fenêtre de sortie',{body:msg,icon:'assets/ebyt-da-logo.png'})}catch(e){}}}
function checkExitWindows(){let changed=false;state.positions=state.positions.map(p=>{const c=posCalc(p);if(c.due&&!p.exitWindowNotified){fireExitNotification(p);changed=true;return{...p,exitWindowNotified:true}}return p});if(changed){persistPositions();renderPositions()}}
function setLang(l){state.lang=l;localStorage.setItem('ebyt-lang',l);$$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));renderCredits();if(state.rows.length){state.rows=state.rows.map(r=>scoreAsset(r,state.market));state.ranked=state.rows.filter(r=>!CONFIG.stable.has(r.symbol)).sort((a,b)=>b.ai-a.ai);state.selected=state.rows.find(r=>r.id===state.selected?.id)||state.ranked[0];renderAll()}}
function setCur(c){if(c===state.cur)return;state.cur=c;localStorage.setItem('ebyt-cur',c);$$('[data-cur]').forEach(b=>b.classList.toggle('active',b.dataset.cur===c));if(state.view==='private')scan(true)}

$('#logoHomeBtn').onclick=showHome;$('#personalSpaceBtn').onclick=()=>state.auth?showDashboard():openAuth();$('#heroPersonalBtn').onclick=()=>state.auth?showDashboard():openAuth();$('#securityPersonalBtn').onclick=()=>state.auth?showDashboard():openAuth();$('#learnMoreBtn').onclick=()=>document.getElementById('howItWorks').scrollIntoView({behavior:'smooth'});$('#logoutBtn').onclick=logout;$('#loginBtn').onclick=login;$$('[data-close-auth]').forEach(e=>e.onclick=closeAuth);$$('[data-public-nav]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.publicNav).scrollIntoView({behavior:'smooth'}));$$('[data-private-nav]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.privateNav).scrollIntoView({behavior:'smooth'}));$('#refreshBtn').onclick=()=>scan(true);$('#refreshPositionsBtn').onclick=()=>refreshPositionPrices(true);$('#search').oninput=renderUniverse;$('#statusFilter').onchange=renderUniverse;$('#openOrderBtn').onclick=openOrder;$('#manualCheck').onchange=e=>$('#confirmOrderBtn').disabled=!e.target.checked;$('#confirmOrderBtn').onclick=confirmOrder;$$('[data-close-order]').forEach(e=>e.onclick=closeOrder);$('#horizonSelect').onchange=()=>{const a=state.selected,val=$('#horizonSelect').value,min=val==='auto'?recommendedHorizonMinutes(a):Number(val);$('#ticketHorizon').textContent=`${horizonLabel(min)}${val==='auto'?' (IA)':''}`};$('#notifyBtn').onclick=requestNotifications;$$('[data-lang]').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));$$('[data-cur]').forEach(b=>b.onclick=()=>setCur(b.dataset.cur));$$('[data-days]').forEach(b=>b.onclick=()=>{$$('[data-days]').forEach(x=>x.classList.toggle('active',x===b));state.chartDays=Number(b.dataset.days);loadChart()});$('#clearHistoryBtn').onclick=()=>{if(confirm("Vider l'historique des positions clôturées ?")){state.closed=[];persistClosed();renderClosed()}};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeAuth();closeOrder()}});$$('[data-cur]').forEach(b=>b.classList.toggle('active',b.dataset.cur===state.cur));$$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));
showHome();renderCredits();
})();