(() => {
'use strict';

const $=(s,p=document)=>p.querySelector(s);
const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0));
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;

const CONFIG={
  marketDataProxy:'/.netlify/functions/marketdata',
  scanMs:15*60*1000,
  priceMs:15*1000,
  universeSize:200,
  candidatePoolSize:500,
  minHistoryDays:730,
  ageCacheDays:30,
  startingCapitalUSDT:3000,
  stakeUSDT:100,
  minPositions:3,
  maxPositions:15,
  maxNewPerScan:5,
  maxHorizonMinutes:5*24*60,
  reentryCooldownMinutes:6*60,
  feeRoundTripPct:0.8733333333,
  feePerSidePct:0.8733333333/2,
  stable:new Set(['usdt','usdc','dai','fdusd','usde','usds','pyusd','tusd','usdd','frax','usdp','gusd','eurs','eurc']),
  posKey:'ebyt-v24-positions',
  closedKey:'ebyt-v24-closed',
  decisionKey:'ebyt-v24-decisions',
  autoKey:'ebyt-v24-autopilot',
  unitKey:'ebyt-v24-unit',
  authKey:'ebyt-v24-auth',
  authEmailKey:'ebyt-v24-auth-email',
  ageCacheKey:'ebyt-v24-age-cache',
  snapshotKey:'ebyt-v24-market-snapshot',
  adminEmail:'admin@ebytda.local',
  demoPass:'EBYTDA-ADMIN-2026'
};

function safeArray(key){try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
const state={
  lang:localStorage.getItem('ebyt-v24-lang')||'fr',
  unit:localStorage.getItem(CONFIG.unitKey)==='eur'?'eur':'usdt',
  view:'home',
  rows:[], ranked:[], market:{label:'—',breadth:50,vol:0}, selected:null, chartDays:1,
  positions:safeArray(CONFIG.posKey), closed:safeArray(CONFIG.closedKey), decisions:safeArray(CONFIG.decisionKey),
  provider:{market:'INIT',marketSource:'',marketFresh:false,marketError:'',prices:'INIT',priceSource:'',priceError:'',lastPriceRefresh:0},
  autoPilot:localStorage.getItem(CONFIG.autoKey)!=='0',
  auth:localStorage.getItem(CONFIG.authKey)==='1', authEmail:localStorage.getItem(CONFIG.authEmailKey)||'',
  fx:{usdtUsd:1,usdtEur:.85}, liveMarket:false, dataMode:'INIT', lastApiError:'', lastScanAt:null,
  nextScan:null,scanTimer:null,countTimer:null,priceTimer:null,scanBusy:false,
  chart:null,candleSeries:null,
  ageCache:(()=>{try{return JSON.parse(localStorage.getItem(CONFIG.ageCacheKey)||'{}')||{}}catch{return{}}})(),
  universeStatus:'INIT', ageChecksThisScan:0,
  marketSnapshot:(()=>{try{return JSON.parse(localStorage.getItem(CONFIG.snapshotKey)||'null')}catch{return null}})()
};

function el(id){return document.getElementById(id)}
function toast(msg){const e=el('toast');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3200)}
function score(v){return num(v).toFixed(2)}
function pct(v,d=2){return Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(d)} %`:'—'}
function klass(v){return num(v)>=0?'pos':'neg'}
function seed(s){let x=0;for(const c of String(s))x=(x*31+c.charCodeAt(0))%1009;return(x%1000)/1000}
function avatar(sym){const t=(sym||'?').toUpperCase().slice(0,3);return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><rect width="100%" height="100%" rx="40" fill="#0e2230"/><text x="50%" y="54%" dominant-baseline="middle" text-anchor="middle" fill="#f3d77f" font-size="24" font-family="Arial" font-weight="700">${t}</text></svg>`)}
function usdtToUnit(v){const x=num(v);return state.unit==='eur'?x*state.fx.usdtEur:x}
function fmtValue(v){const x=usdtToUnit(v);if(state.unit==='eur')return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:Math.abs(x)<1?6:2}).format(x);return `${x.toLocaleString('fr-FR',{maximumFractionDigits:Math.abs(x)<1?6:2})} USDT`}
function fmtCompactUsd(v){const usdt=num(v)/Math.max(state.fx.usdtUsd,.000001),x=usdtToUnit(usdt);if(state.unit==='eur')return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',notation:'compact',maximumFractionDigits:1}).format(x);return `${new Intl.NumberFormat('fr-FR',{notation:'compact',maximumFractionDigits:1}).format(x)} USDT`}
function fee(notional,sideCount=1){return Math.max(0,num(notional))*CONFIG.feePerSidePct/100*sideCount}
function persist(){localStorage.setItem(CONFIG.posKey,JSON.stringify(state.positions));localStorage.setItem(CONFIG.closedKey,JSON.stringify(state.closed));localStorage.setItem(CONFIG.decisionKey,JSON.stringify(state.decisions));localStorage.setItem(CONFIG.autoKey,state.autoPilot?'1':'0');localStorage.setItem(CONFIG.unitKey,state.unit);localStorage.setItem(CONFIG.ageCacheKey,JSON.stringify(state.ageCache));if(state.marketSnapshot)localStorage.setItem(CONFIG.snapshotKey,JSON.stringify(state.marketSnapshot))}

const TR={
  fr:{dashboard:'Dashboard',positions:'Positions',top300:'Top 200 • 2 ans+',history:'Historique',space:'Espace personnel',logout:'Déconnexion',refresh:'Actualiser',notify:'Activer notifications',liveBook:'Positions ouvertes — 3 minimum / 15 maximum'},
  en:{dashboard:'Dashboard',positions:'Positions',top300:'Top 200 • 2y+',history:'History',space:'Personal space',logout:'Sign out',refresh:'Refresh',notify:'Enable notifications',liveBook:'Open positions — 3 minimum / 15 maximum'}
};
function applyLanguage(){
  const t=TR[state.lang];
  const nav=$$('[data-private-nav]'); if(nav[0])nav[0].textContent=t.dashboard;if(nav[1])nav[1].textContent=t.positions;if(nav[2])nav[2].textContent=t.top300;if(nav[3])nav[3].textContent=t.history;
  if(el('personalSpaceBtn'))el('personalSpaceBtn').textContent=t.space;if(el('logoutBtn'))el('logoutBtn').textContent=t.logout;if(el('notifyBtn'))el('notifyBtn').textContent=t.notify;if(el('refreshBtn'))el('refreshBtn').title=t.refresh;
  const intro=$('#radar .intro p');if(intro)intro.textContent=state.lang==='en'?'200 mature cryptos (2+ years) • multi-timeframe AI • scan every 15 min • LONG + SHORT • 100 USDT without leverage':'200 cryptos matures (2 ans+) • IA multi-timeframe • scan toutes les 15 min • LONG + SHORT • 100 USDT sans levier';
  $$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));
}

function showHome(){state.view='home';el('publicHome')?.classList.remove('hidden');el('privateApp')?.classList.add('hidden');el('publicNav')?.classList.remove('hidden');el('privateNav')?.classList.add('hidden');$$('.private-only').forEach(x=>x.classList.add('hidden'));el('personalSpaceBtn')?.classList.remove('hidden');clearTimers();window.scrollTo({top:0})}
async function showDashboard(){if(!state.auth){openAuth();return}state.view='private';el('publicHome')?.classList.add('hidden');el('privateApp')?.classList.remove('hidden');el('publicNav')?.classList.add('hidden');el('privateNav')?.classList.remove('hidden');$$('.private-only').forEach(x=>x.classList.remove('hidden'));el('personalSpaceBtn')?.classList.add('hidden');renderProviderStatus();renderAutoUI();applyLanguage();if(!state.rows.length)await scan(false);else renderAll();startPriceTimer();setTimeout(()=>el('radar')?.scrollIntoView({block:'start'}),10)}
function openAuth(){el('authModal')?.classList.add('open');el('authModal')?.setAttribute('aria-hidden','false');if(el('adminEmail'))el('adminEmail').value=CONFIG.adminEmail;setTimeout(()=>el('adminPass')?.focus(),50)}
function closeAuth(){el('authModal')?.classList.remove('open');el('authModal')?.setAttribute('aria-hidden','true')}
function login(){const email=(el('adminEmail')?.value||'').trim().toLowerCase(),pass=el('adminPass')?.value||'';if(email!==CONFIG.adminEmail||pass!==CONFIG.demoPass){toast('Identifiants administrateur invalides.');return}state.auth=true;state.authEmail=email;localStorage.setItem(CONFIG.authKey,'1');localStorage.setItem(CONFIG.authEmailKey,email);closeAuth();showDashboard()}
function logout(){state.auth=false;localStorage.removeItem(CONFIG.authKey);localStorage.removeItem(CONFIG.authEmailKey);showHome();toast('Session fermée.')}
function clearTimers(){clearTimeout(state.scanTimer);clearInterval(state.countTimer);clearInterval(state.priceTimer);state.scanTimer=state.countTimer=state.priceTimer=null}

function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function fetchJson(url,tries=2,timeout=10000){let last;for(let i=0;i<tries;i++){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{accept:'application/json'},signal:c.signal,cache:'no-store'});const j=await r.json().catch(()=>null);if(!r.ok)throw Object.assign(new Error(j?.error||j?.message||`HTTP ${r.status}`),{status:r.status,payload:j});return j}catch(e){last=e;if(i<tries-1)await sleep(800*(i+1))}finally{clearTimeout(timer)}}throw last}
const DIRECT_DATA={paprika:'https://api.coinpaprika.com/v1',binance:['https://api.binance.com','https://data-api.binance.vision'],frankfurter:'https://api.frankfurter.dev/v2'};
async function directBinance(path,tries=1,timeout=9000){let last;for(const base of DIRECT_DATA.binance){try{return await fetchJson(`${base}${path}`,tries,timeout)}catch(e){last=e}}throw last||new Error('Binance direct indisponible')}
function paprikaYears(x){const t=Date.parse(x?.first_data_at||'');return Number.isFinite(t)?Math.max(0,(Date.now()-t)/(365.25*86400000)):0}
async function directUniverse(){const ticks=await fetchJson(`${DIRECT_DATA.paprika}/tickers?quotes=USD`,2,22000);if(!Array.isArray(ticks))throw new Error('CoinPaprika direct: réponse invalide');let bp={};try{const all=await directBinance('/api/v3/ticker/price',1,9000);for(const x of (Array.isArray(all)?all:[])){const px=num(x?.price);if(px>0)bp[String(x?.symbol||'').toUpperCase()]=px}}catch{}const cutoff=Date.now()-CONFIG.minHistoryDays*86400000,rows=[];for(const x of ticks){const sym=String(x?.symbol||'').toLowerCase(),rank=num(x?.rank,999999),first=Date.parse(x?.first_data_at||''),q=x?.quotes?.USD||{},price=num(q?.price),mcap=num(q?.market_cap);if(!sym||CONFIG.stable.has(sym)||rank<=0||price<=0||mcap<=0||!Number.isFinite(first)||first>cutoff)continue;const bs=String(x.symbol||'').toUpperCase().replace(/[^A-Z0-9]/g,''),bpx=num(bp[`${bs}USDT`]),cross=bpx>0&&Math.abs(bpx/price-1)<=.15;rows.push({id:x.id||`paprika-${rank}-${sym}`,provider_id:x.id||'',symbol:sym,name:x.name||x.symbol,image:'',current_price:cross?bpx:price,market_cap_rank:rank,market_cap:mcap,total_volume:num(q?.volume_24h),price_change_percentage_15m_in_currency:num(q?.percent_change_15m),price_change_percentage_30m_in_currency:num(q?.percent_change_30m),price_change_percentage_1h_in_currency:num(q?.percent_change_1h),price_change_percentage_6h_in_currency:num(q?.percent_change_6h),price_change_percentage_12h_in_currency:num(q?.percent_change_12h),price_change_percentage_24h:num(q?.percent_change_24h),price_change_percentage_7d_in_currency:num(q?.percent_change_7d),price_change_percentage_14d_in_currency:null,price_change_percentage_30d_in_currency:num(q?.percent_change_30d),price_change_percentage_200d_in_currency:null,price_change_percentage_1y_in_currency:num(q?.percent_change_1y),first_data_at:x.first_data_at||null,historyYears:paprikaYears(x),mature2y:true,mtfFull:false,source:'COINPAPRIKA DIRECT',last_updated:x.last_updated||new Date().toISOString(),ath_date:q?.ath_date||null,ath_change_percentage:num(q?.percent_from_price_ath,-50),binanceListed:cross});if(rows.length>=CONFIG.universeSize)break}if(rows.length<CONFIG.universeSize)throw new Error(`CoinPaprika direct: ${rows.length}/200 actifs matures`);return{ok:true,source:'COINPAPRIKA DIRECT + BINANCE DIRECT',fresh:true,rows:rows.slice(0,CONFIG.universeSize),updatedAt:new Date().toISOString(),maturityVerified:true}}
async function directPrices(symbols=[]){const syms=[...new Set(symbols.map(x=>String(x||'').toUpperCase().replace(/[^A-Z0-9]/g,'')).filter(Boolean))].slice(0,80);if(!syms.length)return{ok:true,source:'BINANCE DIRECT',fresh:true,prices:{}};const q=encodeURIComponent(JSON.stringify(syms.map(s=>`${s}USDT`))),data=await directBinance(`/api/v3/ticker/price?symbols=${q}`,1,7500),prices={};for(const x of (Array.isArray(data)?data:[data])){const pair=String(x?.symbol||'').toUpperCase(),sym=pair.replace(/USDT$/,''),px=num(x?.price);if(sym&&px>0)prices[sym]=px}return{ok:true,source:'BINANCE DIRECT',fresh:Object.keys(prices).length>0,prices,updatedAt:new Date().toISOString()}}
function directInterval(days){const d=num(days,1);if(d<=1)return{interval:'15m',limit:96};if(d<=7)return{interval:'1h',limit:168};if(d<=14)return{interval:'2h',limit:168};if(d<=30)return{interval:'4h',limit:180};if(d<=90)return{interval:'12h',limit:180};return{interval:'1d',limit:Math.min(365,Math.max(90,Math.round(d)))}}
async function directKlines(symbol,days){const s=String(symbol||'').toUpperCase().replace(/[^A-Z0-9]/g,'');if(!s)throw new Error('Symbole invalide');const {interval,limit}=directInterval(days),data=await directBinance(`/api/v3/klines?symbol=${encodeURIComponent(s+'USDT')}&interval=${interval}&limit=${limit}`,1,8000);if(!Array.isArray(data))throw new Error('Bougies Binance direct invalides');return{ok:true,source:'BINANCE DIRECT',symbol:s,interval,rows:data.map(x=>[num(x[0]),num(x[1]),num(x[2]),num(x[3]),num(x[4])])}}
function closePct(rows,back){const c=(rows||[]).map(x=>num(x?.[4])).filter(x=>x>0);if(c.length<2)return null;const last=c.at(-1),old=c[Math.max(0,c.length-1-back)];return last>0&&old>0?(last/old-1)*100:null}
async function directDeep(symbols=[]){const wanted=[...new Set(symbols.map(x=>String(x||'').toUpperCase().replace(/[^A-Z0-9]/g,'')).filter(Boolean))].slice(0,36),rows=[];for(let i=0;i<wanted.length;i+=6){const res=await Promise.allSettled(wanted.slice(i,i+6).map(async s=>{const k=await directBinance(`/api/v3/klines?symbol=${encodeURIComponent(s+'USDT')}&interval=1d&limit=365`,1,8000);if(!Array.isArray(k)||k.length<210)throw new Error(`${s}: historique Binance insuffisant`);const d14=closePct(k,14),d30=closePct(k,30),d200=closePct(k,200),y1=k.length>=360?closePct(k,364):null;return{symbol:s,d14,d30,d200,y1,full:[d14,d30,d200,y1].every(Number.isFinite)}}));for(const r of res)if(r.status==='fulfilled')rows.push(r.value)}return{ok:true,source:'BINANCE DIRECT DAILY',rows,updatedAt:new Date().toISOString()}}
async function directFx(){const j=await fetchJson(`${DIRECT_DATA.frankfurter}/rate/usd/eur`,2,7000);return{ok:true,source:'FRANKFURTER DIRECT',usdEur:num(j?.rate,.85),updatedAt:new Date().toISOString()}}
async function fetchMarketData(params={},tries=2,timeout=12000){const mode=String(params?.mode||'').toLowerCase();try{if(mode==='universe')return await directUniverse();if(mode==='prices')return await directPrices(String(params?.symbols||'').split(','));if(mode==='deep')return await directDeep(String(params?.symbols||'').split(','));if(mode==='klines')return await directKlines(params?.symbol,params?.days);if(mode==='fx')return await directFx()}catch(directErr){const qs=new URLSearchParams(params).toString();try{return await fetchJson(`${CONFIG.marketDataProxy}?${qs}`,1,timeout)}catch(proxyErr){throw new Error(`Direct: ${directErr?.message||directErr} • Proxy: ${proxyErr?.message||proxyErr}`)}}const qs=new URLSearchParams(params).toString();return fetchJson(`${CONFIG.marketDataProxy}?${qs}`,tries,timeout)}
async function fetchFx(){try{const j=await fetchMarketData({mode:'fx'},2,9000);state.fx.usdtUsd=1;state.fx.usdtEur=num(j?.usdEur,state.fx.usdtEur)}catch(e){state.fx.usdtUsd=1;state.lastApiError=String(e?.message||e)}}
async function fetchMarketCandidates(){
  const payload=await fetchMarketData({mode:'universe'},2,28000);
  const rows=Array.isArray(payload?.rows)?payload.rows:[];
  if(rows.length<CONFIG.universeSize)throw new Error(`Data engine incomplet ${rows.length}/${CONFIG.universeSize}`);
  state.provider.market=payload.fresh===false?'CACHE':'LIVE';
  state.provider.marketSource=payload.source||'MULTI-SOURCE';
  state.provider.marketFresh=payload.fresh!==false;
  state.provider.marketError=payload.warning||'';
  for(const r of rows){if(r?.mature2y&&r?.id){state.ageCache[r.id]={eligible:true,genesisDate:r.first_data_at||null,evidence:'COINPAPRIKA DIRECT FIRST_DATA_AT',checkedAt:Date.now()}}}
  persist();
  return rows.slice(0,CONFIG.universeSize);
}
function oldestKnownMarketDate(r){const vals=[r?.first_data_at,r?.ath_date,r?.atl_date].map(x=>Date.parse(x)).filter(Number.isFinite);return vals.length?Math.min(...vals):NaN}
function historyYearsFromRow(r){if(num(r?.historyYears)>0)return num(r.historyYears);const t=oldestKnownMarketDate(r);return Number.isFinite(t)?Math.max(0,(Date.now()-t)/(365.25*86400000)):0}
function cacheAge(id,eligible,genesisDate=null,evidence=''){state.ageCache[id]={eligible:!!eligible,genesisDate:genesisDate||null,evidence,checkedAt:Date.now()};persist()}
function cachedAge(id){const c=state.ageCache[id];if(!c)return null;if(Date.now()-num(c.checkedAt)>CONFIG.ageCacheDays*86400000)return null;return c}
async function verifyMaturity(r){return historyYearsFromRow(r)>=2}
async function buildMatureUniverse(rows){
  const out=rows.filter(r=>!CONFIG.stable.has(String(r.symbol||'').toLowerCase())&&historyYearsFromRow(r)>=2&&num(r.current_price)>0)
    .sort((a,b)=>num(a.market_cap_rank,9999)-num(b.market_cap_rank,9999)).slice(0,CONFIG.universeSize)
    .map(r=>({...r,historyYears:historyYearsFromRow(r),mature2y:true}));
  if(out.length<CONFIG.universeSize)throw new Error(`Univers mature incomplet ${out.length}/${CONFIG.universeSize}`);
  return out;
}
function demoData(){const n=[['bitcoin','btc','Bitcoin'],['ethereum','eth','Ethereum'],['tether','usdt','Tether'],['binancecoin','bnb','BNB'],['solana','sol','Solana'],['usd-coin','usdc','USDC'],['ripple','xrp','XRP'],['dogecoin','doge','Dogecoin'],['cardano','ada','Cardano'],['avalanche-2','avax','Avalanche'],['chainlink','link','Chainlink'],['polkadot','dot','Polkadot'],['tron','trx','TRON'],['litecoin','ltc','Litecoin'],['uniswap','uni','Uniswap'],['internet-computer','icp','Internet Computer'],['near','near','NEAR'],['aptos','apt','Aptos'],['arbitrum','arb','Arbitrum'],['optimism','op','Optimism'],['render-token','render','Render'],['sui','sui','Sui'],['aave','aave','Aave'],['cosmos','atom','Cosmos'],['stellar','xlm','Stellar'],['filecoin','fil','Filecoin'],['injective-protocol','inj','Injective'],['the-graph','grt','The Graph'],['maker','mkr','Maker']];while(n.length<200){const i=n.length+1;n.push([`asset-${i}`,`c${i}`,`Crypto ${i}`])}return n.map((c,i)=>{const s=seed(c[0]),p=i<5?[65000,3500,1,600,150][i]:Math.max(.03,240/(i+1)*(.6+s));return{id:c[0],symbol:c[1],name:c[2],image:'',current_price:p,market_cap_rank:i+1,market_cap:p*(1.2e9/(i+1)),total_volume:p*(6e7/(i+1))*(1+s*2),price_change_percentage_1h_in_currency:(s-.5)*7,price_change_percentage_24h:(seed(c[1]+'d')-.46)*16,price_change_percentage_7d_in_currency:(seed(c[1]+'w')-.44)*30,price_change_percentage_30d_in_currency:(seed(c[1]+'m')-.45)*55,price_change_percentage_14d_in_currency:(seed(c[1]+'2w')-.45)*38,price_change_percentage_200d_in_currency:(seed(c[1]+'200d')-.45)*95,price_change_percentage_1y_in_currency:(seed(c[1]+'1y')-.45)*140,historyYears:2.5+seed(c[0]+'age')*8,ath_date:'2020-01-01T00:00:00.000Z',atl_date:'2020-01-01T00:00:00.000Z',ath_change_percentage:-8-(1-s)*75}})}

function marketStats(rows){const tr=rows.filter(r=>!CONFIG.stable.has(r.symbol));const breadth=tr.length?tr.filter(r=>num(r.price_change_percentage_24h)>=0).length/tr.length*100:50;const btc=rows.find(r=>r.symbol==='btc')||tr[0],eth=rows.find(r=>r.symbol==='eth')||tr[1],b24=num(btc?.price_change_percentage_24h),e24=num(eth?.price_change_percentage_24h),avg7=tr.length?tr.reduce((a,r)=>a+num(r.price_change_percentage_7d_in_currency),0)/tr.length:0,vol=tr.length?tr.reduce((a,r)=>a+Math.abs(num(r.price_change_percentage_24h)),0)/tr.length:0;let label='RANGE / MIXTE',base=60;if(breadth>62&&b24>1){label='RISK-ON';base=80}else if(breadth<38&&b24<-1){label='RISK-OFF';base=42}else if(Math.abs(b24)<.8&&Math.abs(avg7)<2){label='MARCHÉ PLAT';base=55}else if(e24>b24+1&&breadth>55){label='ROTATION ALTCOINS';base=77}if(vol>5)label+=' • VOLATIL';return{breadth,btc,eth,b24,e24,avg7,vol,label,base}}
function tfComponent(change,scale,dir){return clamp(50+dir*num(change)/Math.max(scale,.001)*50)}
function scoreAsset(r,m){
  const m15=num(r.price_change_percentage_15m_in_currency),m30=num(r.price_change_percentage_30m_in_currency),h1=num(r.price_change_percentage_1h_in_currency),h6=num(r.price_change_percentage_6h_in_currency),h12=num(r.price_change_percentage_12h_in_currency),d1=num(r.price_change_percentage_24h),d7=num(r.price_change_percentage_7d_in_currency),d14=num(r.price_change_percentage_14d_in_currency),d30=num(r.price_change_percentage_30d_in_currency),d200=num(r.price_change_percentage_200d_in_currency),y1=num(r.price_change_percentage_1y_in_currency);
  const vmc=num(r.total_volume)/Math.max(num(r.market_cap),1),rank=num(r.market_cap_rank,350),ath=num(r.ath_change_percentage,-50),historyYears=Math.max(2,num(r.historyYears,historyYearsFromRow(r)||2));
  const tfs=[['15M',m15,3,.04],['30M',m30,4,.05],['1H',h1,5,.07],['6H',h6,8,.08],['12H',h12,10,.08],['24H',d1,14,.10],['7J',d7,28,.14],['14J',d14,38,.10],['30J',d30,55,.12],['200J',d200,100,.11],['1AN',y1,160,.11]];
  const longMtf=tfs.reduce((s,x)=>s+tfComponent(x[1],x[2],1)*x[3],0),shortMtf=tfs.reduce((s,x)=>s+tfComponent(x[1],x[2],-1)*x[3],0);
  const longAlign=tfs.reduce((s,x)=>s+(x[1]>=0?x[3]:0),0)*100,shortAlign=tfs.reduce((s,x)=>s+(x[1]<=0?x[3]:0),0)*100;
  const volume=clamp(35+Math.log10(Math.max(vmc,.0001)*10000)*14),stability=clamp(90-Math.abs(d1)*2.0-Math.max(0,Math.abs(h1)-3)*3-Math.max(0,Math.abs(m15)-2)*3),cap=clamp(94-Math.log10(Math.max(rank,1))*19),liquidity=clamp(35+Math.log10(Math.max(num(r.total_volume),1))*5.3),recovery=clamp(90+ath*.4),maturity=clamp(58+(historyYears-2)*7,58,100),fund=clamp(cap*.36+liquidity*.28+recovery*.16+maturity*.20);
  const lm=clamp(50+m15*7+m30*5+h1*5+h6*2+h12*1.3+d1*1.5),sm=clamp(50-m15*7-m30*5-h1*5-h6*2-h12*1.3-d1*1.5),lt=clamp(50+d1*1.5+d7*.9+d14*.55+d30*.30+d200*.12+y1*.07),st=clamp(50-d1*1.5-d7*.9-d14*.55-d30*.30-d200*.12-y1*.07);
  const longTech=clamp(lm*.23+lt*.20+longMtf*.34+volume*.14+stability*.09),shortTech=clamp(sm*.23+st*.20+shortMtf*.34+volume*.14+stability*.09);
  const longQuant=clamp(longTech*.34+longMtf*.22+volume*.18+stability*.12+liquidity*.09+maturity*.05),shortQuant=clamp(shortTech*.34+shortMtf*.22+volume*.18+stability*.12+liquidity*.09+maturity*.05);
  const rel=d1-num(m.b24),longRegime=clamp(m.base+rel*2.4+(m.breadth-50)*.25),shortRegime=clamp((100-m.base)+(-rel)*2.2+(50-m.breadth)*.35+Math.max(0,-num(m.b24))*2.2);
  const la=clamp(50+m15*7+m30*5+h1*4+(d1-h1*4)*2.2),sa=clamp(50-m15*7-m30*5-h1*4-(d1-h1*4)*2.2),longFomo=clamp(la*.28+volume*.18+longTech*.16+longQuant*.12+longRegime*.12+longMtf*.14),shortFomo=clamp(sa*.28+volume*.18+shortTech*.16+shortQuant*.12+shortRegime*.12+shortMtf*.14);
  const pen=Math.max(0,Math.abs(d1)-13)*1.0+Math.max(0,Math.abs(h1)-7)*1.4+Math.max(0,Math.abs(m15)-5)*1.2;
  const longAlignPenalty=Math.max(0,53-longAlign)*.20,shortAlignPenalty=Math.max(0,53-shortAlign)*.20;
  const longAi=clamp(longTech*.18+longQuant*.16+fund*.14+longRegime*.15+longFomo*.15+longMtf*.22-pen-longAlignPenalty),shortAi=clamp(shortTech*.18+shortQuant*.16+fund*.14+shortRegime*.15+shortFomo*.15+shortMtf*.22-pen-shortAlignPenalty);
  const preferredSide=shortAi>longAi?'short':'long',tech=preferredSide==='short'?shortTech:longTech,quant=preferredSide==='short'?shortQuant:longQuant,regime=preferredSide==='short'?shortRegime:longRegime,fomo=preferredSide==='short'?shortFomo:longFomo,ai=preferredSide==='short'?shortAi:longAi,mtf=preferredSide==='short'?shortMtf:longMtf,mtfAlignment=preferredSide==='short'?shortAlign:longAlign;
  const volPct=clamp(Math.abs(m15)*.6+Math.abs(h1)*.7+Math.abs(d1)*.28+Math.abs(d7)*.07+1.1,1.5,11),risk=clamp(ai*.30+quant*.17+regime*.17+fund*.11+liquidity*.10+mtf*.15-Math.max(0,volPct-6)*3-Math.max(0,50-mtfAlignment)*.22),edge=Math.abs(longAi-shortAi),opportunity=clamp(ai*.60+fomo*.16+risk*.10+mtf*.14),price=num(r.current_price)/Math.max(state.fx.usdtUsd,.000001),mtfFull=!!r.mtfFull;
  let status='neutral',label=mtfFull?'NEUTRE':'MTF À COMPLÉTER';if(mtfFull&&ai>=80&&fomo>=70&&regime>=52&&mtf>=68&&mtfAlignment>=62){status='order';label='ORDRE CONSEILLÉ'}else if(mtfFull&&ai>=72&&fomo>=60&&mtf>=61&&mtfAlignment>=55){status='preorder';label='PRÉ-ORDRE'}else if(mtfFull&&ai>=62){status='watch';label='À SURVEILLER'}
  const tfText=`15M ${pct(m15,1)} • 30M ${pct(m30,1)} • 1H ${pct(h1,1)} • 6H ${pct(h6,1)} • 12H ${pct(h12,1)} • 24H ${pct(d1,1)} • 7J ${pct(d7,1)} • 14J ${pct(d14,1)} • 30J ${pct(d30,1)} • 200J ${pct(d200,1)} • 1AN ${pct(y1,1)}`;
  const reason=[preferredSide.toUpperCase(),`MTF ${score(mtf)}/100`,`${mtfAlignment.toFixed(0)}% horizons alignés`,mtfFull?'MTF complet':'MTF long en cours',tech>72?'momentum solide':'momentum moyen',regime>68?'régime favorable':'régime mixte'].join(' • ');
  return{...r,currentPriceUSDT:price,tech,quant,fund,regime,fomo,ai,risk,longAi,shortAi,longTech,shortTech,longRegime,shortRegime,longFomo,shortFomo,longMtf,shortMtf,mtf,mtfAlignment,timeframeText:tfText,preferredSide,directionEdge:edge,opportunityScore:opportunity,volatilityPricePct:volPct,status,label,reason,historyYears,maturity,mtfFull,entryLow:price*.997,entryHigh:price*1.002}
}
function chooseSide(a){return a?.preferredSide==='short'?'short':'long'}
function rankOf(a){const i=state.ranked.findIndex(x=>x.id===a?.id);return i>=0?i+1:null}
function positionByAsset(id){return state.positions.find(p=>p.assetId===id)}
function recentClosed(id){return state.closed.some(p=>p.assetId===id&&Date.now()-new Date(p.closedAt).getTime()<CONFIG.reentryCooldownMinutes*60000)}
function horizonMinutes(a){const structural=(num(a.quant)+num(a.fund)+num(a.regime))/3,v=num(a.volatilityPricePct);if(a.ai>=90&&a.fomo>=86&&v>5)return 360;if(a.ai>=85&&a.fomo>=78)return 720;if(a.ai>=80&&structural>=74)return 1440;if(structural>=70&&a.risk>=68)return 2880;if(a.ai>=70)return 4320;return 5760}
function horizonLabel(m){if(m<60)return`${m} min`;if(m<1440)return`${Math.round(m/60)} h`;return`${(m/1440).toFixed(m%1440?1:0)} j`}
function remainingLabel(ms){if(ms<=0)return'FENÊTRE ARRIVÉE';const m=Math.ceil(ms/60000);if(m<60)return`${m} min`;if(m<1440)return`${Math.floor(m/60)} h ${m%60} min`;return`${Math.floor(m/1440)} j ${Math.floor((m%1440)/60)} h`}

function positionCalc(p){const entry=num(p.entryPriceUSDT),cur=num(p.currentPriceUSDT,entry),side=p.side==='short'?-1:1,qty=entry>0?CONFIG.stakeUSDT/entry:0,gross=qty*(cur-entry)*side,entryFee=fee(CONFIG.stakeUSDT,1),exitFee=fee(Math.max(0,qty*cur),1),net=gross-entryFee-exitFee,pnlPct=net/CONFIG.stakeUSDT*100,target=new Date(p.targetCloseAt).getTime(),remaining=Math.max(0,target-Date.now());return{entry,cur,qty,gross,entryFee,exitFee,net,pnlPct,remaining,due:Date.now()>=target}}
function accountStats(){const realized=state.closed.reduce((s,p)=>s+num(p.netPnlUSDT),0),realizedCapital=CONFIG.startingCapitalUSDT+realized,engaged=state.positions.length*CONFIG.stakeUSDT,available=realizedCapital-engaged,latent=state.positions.reduce((s,p)=>s+positionCalc(p).net,0),equity=realizedCapital+latent;return{realized,realizedCapital,engaged,available,latent,equity}}
function validPosition(p){const e=num(p?.entryPriceUSDT),c=num(p?.currentPriceUSDT,e);return p&&p.assetId&&p.symbol&&['long','short'].includes(p.side)&&e>0&&c>0&&Number.isFinite(e)&&Number.isFinite(c)&&p.openedAt&&p.targetCloseAt&&num(p.stakeUSDT,CONFIG.stakeUSDT)>0}
function sanitizeState(){state.positions=state.positions.filter(validPosition).slice(0,CONFIG.maxPositions);state.closed=state.closed.filter(p=>p&&Number.isFinite(num(p.netPnlUSDT))&&p.closedAt).slice(0,1500);persist()}

function autoDecision(a){const s=accountStats(),side=chooseSide(a);if(positionByAsset(a.id))return{ok:false,action:'HOLD',side,why:'déjà ouvert'};if(recentClosed(a.id))return{ok:false,action:'COOLDOWN',side,why:'réentrée 6 h'};if(state.positions.length>=CONFIG.maxPositions)return{ok:false,action:'FULL',side,why:'15 positions ouvertes'};if(s.available<CONFIG.stakeUSDT)return{ok:false,action:'NO CAPITAL',side,why:'capital disponible insuffisant'};if(!a.mature2y||num(a.currentPriceUSDT)<=0||!a.binanceListed)return{ok:false,action:'WAIT',side,why:'actif non valide / flux Binance non confirmé'};if(!a.mtfFull)return{ok:false,action:'WAIT',side,why:'MTF long non validé'};if(a.ai<66||a.fomo<54||a.risk<50||a.mtf<57||a.mtfAlignment<50)return{ok:false,action:'WAIT',side,why:'consensus multi-timeframe insuffisant'};if(a.directionEdge<1.2&&a.ai<76)return{ok:false,action:'WAIT',side,why:'direction trop indécise'};return{ok:true,action:`AUTO ${side.toUpperCase()}`,side,why:`IA ${score(a.ai)} • MTF ${score(a.mtf)} • Align ${a.mtfAlignment.toFixed(0)}% • Risk ${score(a.risk)}`}}
function coreDecision(a){const s=accountStats(),side=chooseSide(a);if(!a||positionByAsset(a.id)||recentClosed(a.id)||state.positions.length>=CONFIG.maxPositions||s.available<CONFIG.stakeUSDT)return{ok:false,side};if(!a.mature2y||num(a.currentPriceUSDT)<=0||!a.mtfFull||!a.binanceListed)return{ok:false,side};if(a.ai<50||a.risk<34||a.directionEdge<.10||a.mtf<46||a.mtfAlignment<40)return{ok:false,side};return{ok:true,side}}
function openPosition(a,{source='AUTO',broker='AUTO PAPER',side=null,entry=null,horizon=null}={}){if(!a||positionByAsset(a.id)||recentClosed(a.id))return false;const s=accountStats();if(state.positions.length>=CONFIG.maxPositions||s.available<CONFIG.stakeUSDT)return false;const livePx=num(a.currentPriceUSDT),px=num(entry,livePx);if(px<=0||livePx<=0)return false;if(Math.abs(px/livePx-1)>.03){toast('Ordre refusé : prix d’entrée écarté de plus de 3 % du LIVE.');return false}const h=clamp(horizon||horizonMinutes(a),60,CONFIG.maxHorizonMinutes),now=Date.now(),sideFinal=side||chooseSide(a);state.positions.unshift({id:crypto.randomUUID?crypto.randomUUID():String(now+Math.random()),assetId:a.id,symbol:a.symbol,name:a.name,image:a.image||'',source,broker,side:sideFinal,stakeUSDT:CONFIG.stakeUSDT,entryPriceUSDT:px,currentPriceUSDT:px,openedAt:new Date(now).toISOString(),targetCloseAt:new Date(now+h*60000).toISOString(),maxCloseAt:new Date(now+CONFIG.maxHorizonMinutes*60000).toISOString(),horizonMinutes:h,extensionCount:0,entryAi:a.ai,entryFomo:a.fomo,entryRisk:a.risk,entryMtf:a.mtf,entryMtfAlignment:a.mtfAlignment,marketPriceAtEntryUSDT:livePx,entryPriceSource:`${state.provider.marketSource||'DATA ENGINE'} LIVE • V26 DIRECT SYNC`,lastAi:a.ai,lastFomo:a.fomo,lastRisk:a.risk,lastMtf:a.mtf,lastMtfAlignment:a.mtfAlignment,maxPnlPct:0,minPnlPct:0,status:'open'});if(String(source).startsWith('AUTO')){state.decisions.unshift({at:new Date(now).toISOString(),rank:rankOf(a)||a.market_cap_rank||0,assetId:a.id,symbol:a.symbol,name:a.name,side:sideFinal,ai:a.ai,fomo:a.fomo,risk:a.risk,mtf:a.mtf,mtfAlignment:a.mtfAlignment,horizonMinutes:h,decision:`OUVERTURE AUTO ${sideFinal.toUpperCase()}`,why:`100 USDT • ${source}`});state.decisions=state.decisions.slice(0,1000)}persist();notifyEvent('EBYTDA • Position ouverte',`${a.symbol.toUpperCase()} ${sideFinal.toUpperCase()} • 100 USDT • horizon ${horizonLabel(h)}`);return true}
function closePosition(p,reason,price=null){if(!p)return;const px=num(price,p.currentPriceUSDT),entry=num(p.entryPriceUSDT),sgn=p.side==='short'?-1:1,qty=entry>0?CONFIG.stakeUSDT/entry:0,gross=qty*(px-entry)*sgn,fees=fee(CONFIG.stakeUSDT,1)+fee(Math.max(0,qty*px),1),net=gross-fees;state.positions=state.positions.filter(x=>x.id!==p.id);state.closed.unshift({...p,status:'closed',closedAt:new Date().toISOString(),exitPriceUSDT:px,closeReason:reason,grossPnlUSDT:gross,feesUSDT:fees,netPnlUSDT:net});state.closed=state.closed.slice(0,1500);persist();notifyEvent('EBYTDA • Position clôturée',`${p.symbol.toUpperCase()} ${p.side.toUpperCase()} • ${reason} • ${fmtValue(net)}`)}
function continuationScore(p,a){if(!a)return num(p.lastAi);const sideAi=p.side==='short'?num(a.shortAi):num(a.longAi);return sideAi*.34+num(a.fomo)*.16+num(a.regime)*.14+num(a.quant)*.14+num(a.mtf)*.22}
function reviewHorizon(p,a){const c=positionCalc(p),max=new Date(p.maxCloseAt).getTime();if(Date.now()>=max){closePosition(p,'HORIZON MAX 5 JOURS',c.cur);return}const cont=continuationScore(p,a),sideAi=a?(p.side==='short'?a.shortAi:a.longAi):num(p.lastAi),opp=a?(p.side==='short'?a.longAi:a.shortAi):0;if(a&&cont>=66&&sideAi>=opp){const room=Math.max(0,max-Date.now()),add=Math.min(room,cont>=78?24*60*60000:cont>=70?12*60*60000:4*60*60000);if(add>60000){p.targetCloseAt=new Date(Date.now()+add).toISOString();p.extensionCount=num(p.extensionCount)+1;persist();return}}closePosition(p,'HORIZON IA — CONTINUATION INSUFFISANTE',c.cur)}
function evaluateExits(){for(const p of [...state.positions]){const a=state.rows.find(x=>x.id===p.assetId);if(!a)continue;p.lastAi=a.ai;p.lastFomo=a.fomo;p.lastRisk=a.risk;p.lastMtf=a.mtf;p.lastMtfAlignment=a.mtfAlignment;const c=positionCalc(p),age=(Date.now()-new Date(p.openedAt).getTime())/60000,sideAi=p.side==='short'?a.shortAi:a.longAi,opp=p.side==='short'?a.longAi:a.shortAi,cont=continuationScore(p,a);p.maxPnlPct=Math.max(num(p.maxPnlPct),c.pnlPct);p.minPnlPct=Math.min(num(p.minPnlPct),c.pnlPct);if(c.due){reviewHorizon(p,a);continue}if(age>=60&&opp>=84&&opp-sideAi>=18&&sideAi<46&&c.pnlPct<0){closePosition(p,'SORTIE IA — RETOURNEMENT FORT',c.cur);continue}if(age>=120&&a.mtf<43&&a.mtfAlignment<42&&sideAi<54&&c.pnlPct<0){closePosition(p,'SORTIE IA — CASSE MULTI-TIMEFRAME',c.cur);continue}if(age>=240&&sideAi<50&&cont<52&&c.pnlPct<0&&opp>sideAi+10){closePosition(p,'SORTIE IA — MOMENTUM CASSÉ',c.cur);continue}if(age>=20&&c.pnlPct>=8&&cont<67){closePosition(p,'PRISE DE GAIN IA — MOUVEMENT RAPIDE',c.cur);continue}if(age>=120&&c.pnlPct>=5&&cont<60){closePosition(p,'PRISE DE GAIN IA — CONTINUATION FAIBLE',c.cur);continue}}persist()}
function runAutoEntries(){if(!state.autoPilot||!state.liveMarket||!state.ranked.length)return 0;let opened=0;const canOpen=()=>state.positions.length<CONFIG.maxPositions&&accountStats().available>=CONFIG.stakeUSDT;
  // Noyau automatique : si le portefeuille contient moins de 3 positions, les meilleurs candidats LIVE valides sont exécutés sans attendre le prochain cycle.
  while(state.positions.length<CONFIG.minPositions&&opened<CONFIG.maxNewPerScan&&canOpen()){
    let a=state.ranked.find(x=>!positionByAsset(x.id)&&!recentClosed(x.id)&&coreDecision(x).ok);
    if(!a)a=state.ranked.find(x=>!positionByAsset(x.id)&&!recentClosed(x.id)&&x.mature2y&&x.mtfFull&&num(x.currentPriceUSDT)>0&&x.ai>=45&&x.mtf>=43&&x.directionEdge>=.05);
    if(!a)break;
    const d=coreDecision(a),side=d.side||chooseSide(a);
    if(openPosition(a,{source:'AUTO CORE EXEC • LIVE',broker:'AUTO PAPER',side,horizon:horizonMinutes(a)}))opened++;else break;
  }
  // Complément opportuniste : jusqu’à 15 positions, avec seuils renforcés quand le portefeuille devient chargé.
  for(const a of state.ranked){
    if(opened>=CONFIG.maxNewPerScan||!canOpen())break;
    if(positionByAsset(a.id)||recentClosed(a.id))continue;
    const d=autoDecision(a);if(!d.ok)continue;
    const crowded=state.positions.length>=10;
    const strict=crowded?(a.ai>=78&&a.fomo>=66&&a.risk>=60&&a.mtf>=66&&a.mtfAlignment>=60&&a.directionEdge>=3.5):(a.ai>=71&&a.fomo>=58&&a.risk>=52&&a.mtf>=59&&a.mtfAlignment>=52&&a.directionEdge>=1.8);
    if(!strict)continue;
    if(openPosition(a,{source:'AUTO OPPORTUNITY EXEC • LIVE',broker:'AUTO PAPER',side:d.side,horizon:horizonMinutes(a)}))opened++;
  }
  if(opened)toast(`AutoPilot : ${opened} ordre(s) papier exécuté(s) • ${state.positions.length}/15`);return opened}
function logTop3(){const at=new Date().toISOString();state.decisions.unshift(...state.ranked.slice(0,3).map((a,i)=>{const d=autoDecision(a);return{at,rank:i+1,assetId:a.id,symbol:a.symbol,name:a.name,side:d.side||chooseSide(a),ai:a.ai,fomo:a.fomo,risk:a.risk,mtf:a.mtf,mtfAlignment:a.mtfAlignment,horizonMinutes:horizonMinutes(a),decision:d.action,why:d.why}}));state.decisions=state.decisions.slice(0,1000);persist()}
async function hydrateDeepTimeframes(){
  const syms=[...new Set([...state.ranked.slice(0,30).map(a=>String(a.symbol||'').toUpperCase()),...state.positions.map(p=>String(p.symbol||'').toUpperCase())].filter(Boolean))].slice(0,36);
  if(!syms.length)return 0;
  try{
    const j=await fetchMarketData({mode:'deep',symbols:syms.join(',')},1,26000),by=new Map((j?.rows||[]).map(x=>[String(x.symbol||'').toUpperCase(),x]));
    let nup=0;
    for(const r of state.rows){const d=by.get(String(r.symbol||'').toUpperCase());if(!d)continue;r.price_change_percentage_14d_in_currency=num(d.d14);r.price_change_percentage_30d_in_currency=num(d.d30);r.price_change_percentage_200d_in_currency=num(d.d200);r.price_change_percentage_1y_in_currency=num(d.y1);r.mtfFull=!!d.full;if(r.mtfFull)nup++}
    const m=marketStats(state.rows);state.market=m;state.rows=state.rows.map(r=>scoreAsset(r,m)).sort((a,b)=>num(a.market_cap_rank)-num(b.market_cap_rank));state.ranked=state.rows.slice().sort((a,b)=>b.opportunityScore-a.opportunityScore);state.selected=state.rows.find(x=>x.id===state.selected?.id)||state.ranked[0]||null;
    return nup;
  }catch(e){state.provider.marketError=`MTF long: ${e?.message||e}`;return 0}
}
async function hydrateRealtimePrices(){
  const syms=[...new Set([...state.ranked.slice(0,25).map(a=>String(a.symbol||'').toUpperCase()),...state.positions.map(p=>String(p.symbol||'').toUpperCase())].filter(Boolean))];
  if(!syms.length)return 0;
  try{
    const j=await fetchMarketData({mode:'prices',symbols:syms.join(',')},2,9000);let nup=0;
    for(const a of state.rows){const px=num(j?.prices?.[String(a.symbol||'').toUpperCase()]);const prev=num(a.currentPriceUSDT);if(px>0&&prev>0&&Math.abs(px/prev-1)<.12){a.currentPriceUSDT=px;a.entryLow=px*.997;a.entryHigh=px*1.002;nup++}}
    for(const p of state.positions){const px=num(j?.prices?.[String(p.symbol||'').toUpperCase()]);const prev=num(p.currentPriceUSDT,p.entryPriceUSDT);if(px>0&&prev>0&&Math.abs(px/prev-1)<.12)p.currentPriceUSDT=px}
    state.provider.prices=nup>0?'LIVE':'PARTIEL';state.provider.priceSource=j?.source||'BINANCE';state.provider.priceError=j?.error||'';state.provider.lastPriceRefresh=Date.now();return nup;
  }catch(e){state.provider.prices='ERREUR';state.provider.priceError=e?.message||String(e);return 0}
}

async function scan(manual=false){if(state.view!=='private'||state.scanBusy)return;state.scanBusy=true;state.provider.market='INIT';state.provider.marketError='';renderProviderStatus();el('refreshBtn')?.classList.add('spin');let raw,live=false;try{await fetchFx();const candidates=await fetchMarketCandidates();raw=await buildMatureUniverse(candidates);live=state.provider.marketFresh!==false;state.liveMarket=live;state.dataMode=live?'LIVE':'CACHE';state.universeStatus=`${raw.length} MATURES • 2 ANS+`;state.lastApiError='';state.marketSnapshot={savedAt:Date.now(),source:state.provider.marketSource,rows:raw};persist()}catch(e){state.lastApiError=String(e?.message||e);state.provider.market='ERREUR';state.provider.marketError=state.lastApiError;const snap=state.marketSnapshot;if(snap?.rows?.length>=CONFIG.universeSize&&Date.now()-num(snap.savedAt)<60*60*1000){raw=snap.rows;state.provider.market='CACHE';state.provider.marketSource=`CACHE ${snap.source||''}`.trim();state.provider.marketFresh=false;state.liveMarket=false;state.dataMode='CACHE';toast('Sources marché indisponibles : dernier snapshot affiché. Nouvelles ouvertures auto suspendues.')}else{raw=demoData();state.provider.marketSource='DEMO';state.provider.marketFresh=false;state.liveMarket=false;state.dataMode='DEMO';toast('Sources marché indisponibles : mode démo. Nouvelles ouvertures auto suspendues.')}}try{const m=marketStats(raw);state.market=m;state.rows=raw.map(r=>scoreAsset(r,m)).sort((a,b)=>num(a.market_cap_rank)-num(b.market_cap_rank));state.ranked=state.rows.slice().sort((a,b)=>b.opportunityScore-a.opportunityScore);state.selected=state.rows.find(x=>x.id===state.selected?.id)||state.ranked[0]||null;if(live){await hydrateDeepTimeframes();await hydrateRealtimePrices();}for(const p of state.positions){const a=state.rows.find(x=>x.id===p.assetId||String(x.symbol).toLowerCase()===String(p.symbol).toLowerCase());if(a&&num(a.currentPriceUSDT)>0)p.currentPriceUSDT=a.currentPriceUSDT}if(live){evaluateExits();logTop3();runAutoEntries()}state.lastScanAt=new Date();persist();scheduleScan();renderAll();if(state.selected)loadChart();if(manual)toast(live?`Scan LIVE • ${state.provider.marketSource} • AutoPilot actif.`:'Données de secours affichées — nouvelles ouvertures auto suspendues.')}catch(e){console.error('EBYTDA engine',e);toast(`Erreur moteur : ${e?.message||e}`);renderCoreStatus(`ERREUR • ${e?.message||'moteur'}`)}finally{state.scanBusy=false;el('refreshBtn')?.classList.remove('spin')}}
function scheduleScan(){clearTimeout(state.scanTimer);clearInterval(state.countTimer);state.nextScan=Date.now()+CONFIG.scanMs;state.scanTimer=setTimeout(()=>scan(false),CONFIG.scanMs);state.countTimer=setInterval(renderCountdown,1000);renderCountdown()}
function renderCountdown(){if(!state.nextScan)return;const s=Math.max(0,Math.floor((state.nextScan-Date.now())/1000)),m=Math.floor(s/60),ss=s%60;if(el('countdown'))el('countdown').textContent=`${m}m ${String(ss).padStart(2,'0')}s`;if(el('scanKpi'))el('scanKpi').textContent=`${m}:${String(ss).padStart(2,'0')}`}
function renderCoreStatus(txt){if(el('marketRegime'))el('marketRegime').textContent=txt}

function renderProviderStatus(){
  const a=el('coinGeckoStatus'),as=el('coinGeckoSub'),b=el('twelveStatus'),bs=el('twelveSub');
  const mst=state.provider.market;
  if(a){a.textContent=mst==='LIVE'?'LIVE':mst==='CACHE'?'CACHE':mst==='ERREUR'?'ERREUR':'INIT';a.className=`kpi-value compact-value ${mst==='LIVE'?'pos':mst==='ERREUR'?'neg':''}`}
  if(as){if(mst==='LIVE')as.textContent=`${state.provider.marketSource||'MULTI-SOURCE'} • Top 200 mature • scan frais`;else if(mst==='CACHE')as.textContent=`${state.provider.marketSource||'CACHE'} • lecture seule pour les nouvelles entrées`;else if(mst==='ERREUR')as.textContent=state.provider.marketError||'Sources marché indisponibles';else as.textContent='CoinPaprika DIRECT • Top 200 matures • Netlify seulement en secours'}
  const pst=state.provider.prices;
  if(b){b.textContent=pst==='LIVE'?'LIVE':pst==='PARTIEL'?'PARTIEL':pst==='ERREUR'?'ERREUR':'PRÊT';b.className=`kpi-value compact-value ${pst==='LIVE'?'pos':pst==='ERREUR'?'neg':''}`}
  if(bs){if(pst==='LIVE'||pst==='PARTIEL')bs.textContent=`${state.provider.priceSource||'BINANCE'} • positions réévaluées toutes les 15 s`;else if(pst==='ERREUR')bs.textContent=state.provider.priceError||'Prix rapides indisponibles';else bs.textContent='Binance DIRECT • positions réévaluées toutes les 15 s'}
}
function renderAutoUI(){if(el('autoPilotToggle'))el('autoPilotToggle').checked=state.autoPilot;if(el('autoPilotLabel'))el('autoPilotLabel').textContent=state.autoPilot?'AUTO ON':'AUTO OFF';if(el('feeProxy'))el('feeProxy').textContent=`${CONFIG.feeRoundTripPct.toFixed(4).replace('.',',')} %`}
function renderKpis(){const s=accountStats();if(el('capitalTotal'))el('capitalTotal').textContent=fmtValue(s.realizedCapital);if(el('capitalFree'))el('capitalFree').textContent=fmtValue(s.available);if(el('marginUsed'))el('marginUsed').textContent=fmtValue(s.engaged);if(el('kpiOpen'))el('kpiOpen').textContent=`${state.positions.length} / ${CONFIG.maxPositions}`;if(el('kpiCapital'))el('kpiCapital').textContent=`${state.positions.length} × 100 USDT = ${fmtValue(s.engaged)} engagés`;if(el('kpiPnl')){el('kpiPnl').textContent=fmtValue(s.equity);el('kpiPnl').className=`kpi-value ${klass(s.latent)}`}if(el('kpiPnlPct'))el('kpiPnlPct').textContent=`${fmtValue(s.latent)} latent • equity théorique`;if(el('realizedPnl')){el('realizedPnl').textContent=fmtValue(s.realized);el('realizedPnl').className=`kpi-value ${klass(s.realized)}`}if(el('unrealizedPnl')){el('unrealizedPnl').textContent=fmtValue(s.latent);el('unrealizedPnl').className=`kpi-value ${klass(s.latent)}`}if(el('capitalTotalSub'))el('capitalTotalSub').textContent='3 000 USDT + P&L net clôturé uniquement';if(el('capitalFreeSub'))el('capitalFreeSub').textContent=`Capital réalisé - ${state.positions.length} × 100 USDT engagés`;if(el('kpiSync'))el('kpiSync').textContent=state.lastScanAt?`Dernier scan ${state.lastScanAt.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'Synchronisation 15 min'}
function renderHero(){const a=state.ranked[0];if(!a)return;if(el('marketRegime'))el('marketRegime').textContent=`${state.liveMarket?'LIVE':'DEMO'} • ${state.market.label}`;if(el('heroImg'))el('heroImg').src=a.image||avatar(a.symbol);if(el('heroName'))el('heroName').textContent=`${a.name} (${a.symbol.toUpperCase()})`;if(el('heroPrice'))el('heroPrice').textContent=fmtValue(a.currentPriceUSDT);if(el('hero24h')){el('hero24h').textContent=pct(a.price_change_percentage_24h);el('hero24h').className=klass(a.price_change_percentage_24h)}if(el('heroScore'))el('heroScore').textContent=score(a.ai);if(el('heroSignal'))el('heroSignal').textContent=a.label;if(el('heroReason'))el('heroReason').textContent=a.reason;if(el('engineTech'))el('engineTech').textContent=score(a.tech);if(el('engineQuant'))el('engineQuant').textContent=score(a.quant);if(el('engineMtf'))el('engineMtf').textContent=score(a.mtf);if(el('engineFund'))el('engineFund').textContent=score(a.fund);if(el('engineRegime'))el('engineRegime').textContent=score(a.regime);if(el('engineFomo'))el('engineFomo').textContent=score(a.fomo)}
function renderTop3(){const box=el('top3');if(!box)return;box.innerHTML=state.ranked.slice(0,3).map((a,i)=>{const d=autoDecision(a),side=d.side||chooseSide(a),cls=d.ok?'order':i===1?'preorder':'watch';return`<article class="fcard ${cls}"><div class="fcard-head"><div class="asset"><img src="${a.image||avatar(a.symbol)}"><div><b>${a.name}</b><small>${a.symbol.toUpperCase()}</small></div></div><button class="rank-btn" data-pick="${a.id}">#${i+1}</button></div><div class="score-line"><div><small>FOMO</small><strong>${score(a.fomo)}</strong></div><span class="side-badge ${side}">${side.toUpperCase()}</span><span class="status-pill ${cls}">${d.ok?'AUTO OUVRIR':d.action}</span></div><p>${a.reason}</p><div class="fmeta"><div><small>IA / MTF</small><b>${score(a.ai)} • ${score(a.mtf)}</b></div><div><small>ALIGN / RISK</small><b>${a.mtfAlignment.toFixed(0)}% • ${score(a.risk)}</b></div><div><small>HORIZON</small><b>${horizonLabel(horizonMinutes(a))}</b></div></div><button class="order-mini-btn" data-order="${a.id}">ORDRE MANUEL →</button></article>`}).join('');$$('[data-pick]',box).forEach(b=>b.onclick=()=>selectAsset(b.dataset.pick,true));$$('[data-order]',box).forEach(b=>b.onclick=e=>{e.stopPropagation();selectAsset(b.dataset.order,false);openOrder()})}
function renderCryptoGrid(){const box=el('cryptoGrid100');if(!box)return;box.innerHTML=`<div class="crypto-list-scroll"><table class="crypto-list-table"><thead><tr><th>#</th><th>Actif</th><th>Prix</th><th>24H</th><th>Tech</th><th>Quant</th><th>Régime</th><th>FOMO</th><th>MTF</th><th>IA</th><th>Sens</th><th>Signal</th></tr></thead><tbody>${state.rows.slice(0,200).map(a=>`<tr data-gridpick="${a.id}"><td>${a.market_cap_rank||'—'}</td><td><div class="asset-line"><img src="${a.image||avatar(a.symbol)}"><div><b>${a.name}</b><small>${a.symbol.toUpperCase()}</small></div></div></td><td>${fmtValue(a.currentPriceUSDT)}</td><td class="${klass(a.price_change_percentage_24h)}">${pct(a.price_change_percentage_24h)}</td><td>${score(a.tech)}</td><td>${score(a.quant)}</td><td>${score(a.regime)}</td><td>${score(a.fomo)}</td><td>${score(a.mtf)}</td><td><span class="score-chip ${a.ai>=80?'high':''}">${score(a.ai)}</span></td><td><span class="side-badge ${chooseSide(a)}">${chooseSide(a).toUpperCase()}</span></td><td><span class="status-pill ${a.status}">${a.label}</span></td></tr>`).join('')}</tbody></table></div>`;$$('[data-gridpick]',box).forEach(r=>r.onclick=()=>selectAsset(r.dataset.gridpick,true))}
function renderTop10(){const box=el('top10Rows');if(!box)return;box.innerHTML=state.ranked.slice(0,10).map((a,i)=>`<tr data-rowpick="${a.id}"><td><button class="table-rank" data-pick="${a.id}">#${i+1}</button></td><td><div class="asset"><img src="${a.image||avatar(a.symbol)}"><div><b>${a.name}</b><small>${a.symbol.toUpperCase()}</small></div></div></td><td>${fmtValue(a.currentPriceUSDT)}</td><td class="${klass(a.price_change_percentage_24h)}">${pct(a.price_change_percentage_24h)}</td><td>${score(a.tech)}</td><td>${score(a.quant)}</td><td>${score(a.fund)}</td><td>${score(a.regime)}</td><td>${score(a.fomo)}</td><td>${score(a.mtf)}</td><td>${score(a.ai)}</td><td><span class="side-badge ${chooseSide(a)}">${chooseSide(a).toUpperCase()}</span></td><td><span class="status-pill ${a.status}">${a.label}</span></td><td><button class="table-order-btn" data-order="${a.id}">ORDRE</button></td></tr>`).join('');$$('[data-pick]',box).forEach(b=>b.onclick=e=>{e.stopPropagation();selectAsset(b.dataset.pick,true)});$$('[data-order]',box).forEach(b=>b.onclick=e=>{e.stopPropagation();selectAsset(b.dataset.order,false);openOrder()});$$('[data-rowpick]',box).forEach(r=>r.onclick=()=>selectAsset(r.dataset.rowpick,true))}
function trackStats(a){return{p90:num(a.price_change_percentage_30d_in_currency)*2.1,posDays:clamp(48+seed(a.id+'p')*30),vol:clamp(Math.abs(num(a.price_change_percentage_24h))*.22+2.8,1,25),dd:-clamp(Math.abs(num(a.ath_change_percentage))*.35,5,65),cont:clamp(22+seed(a.id+'c')*58)}}
function renderSelected(){const a=state.selected;if(!a)return;const side=chooseSide(a),sideAi=side==='short'?a.shortAi:a.longAi,opp=side==='short'?a.longAi:a.shortAi,cont=continuationScore({side,lastAi:a.ai},a),tr=trackStats(a),rank=rankOf(a),eligible=state.ranked.slice(0,10).some(x=>x.id===a.id);if(el('chartImg'))el('chartImg').src=a.image||avatar(a.symbol);if(el('chartName'))el('chartName').textContent=a.name;if(el('chartSymbol'))el('chartSymbol').textContent=`${a.symbol.toUpperCase()} • ${side.toUpperCase()}`;if(el('chartPrice'))el('chartPrice').textContent=fmtValue(a.currentPriceUSDT);if(el('chartChange')){el('chartChange').textContent=pct(a.price_change_percentage_24h);el('chartChange').className=`price-change ${klass(a.price_change_percentage_24h)}`}if(el('chartRank'))el('chartRank').textContent=rank?`TOP ${rank}`:`#${a.market_cap_rank}`;if(el('chartEligibility')){el('chartEligibility').textContent=eligible?`✓ TOP ${rank} • ordre manuel autorisé`:'Graphique seul • hors TOP 10';el('chartEligibility').className=`eligibility ${eligible?'yes':''}`}if(el('selectedStatus'))el('selectedStatus').textContent=`${side.toUpperCase()} • ${a.label}`;if(el('selectedScore'))el('selectedScore').textContent=score(a.ai);[['selTech',a.tech],['selQuant',a.quant],['selFund',a.fund],['selRegime',a.regime],['selFomo',a.fomo],['selRisk',a.risk],['selMtf',a.mtf]].forEach(([id,v])=>{if(el(id))el(id).textContent=score(v)});if(el('selLeverage'))el('selLeverage').textContent='100 USDT';if(el('entryZone'))el('entryZone').textContent=`${fmtValue(a.entryLow)} – ${fmtValue(a.entryHigh)}`;if(el('stopLevel'))el('stopLevel').textContent='IA dynamique';if(el('tp1Level'))el('tp1Level').textContent='IA dynamique';if(el('tp2Level'))el('tp2Level').textContent='5 jours max';if(el('selectedReason'))el('selectedReason').textContent=`${a.reason}. ${a.timeframeText}. Historique ≥ 2 ans. Multi-timeframe 15 min → 1 an (Binance MTF long validé avant AutoPilot). Réévaluation IA toutes les 15 min. Horizon ${horizonLabel(horizonMinutes(a))}.`;if(el('gain1'))el('gain1').textContent=score(sideAi);if(el('gain2'))el('gain2').textContent=score(cont);if(el('gain3'))el('gain3').textContent=sideAi>=opp?'HOLD / SURVEILLER':'RISQUE DE RETOURNEMENT';if(el('openOrderBtn'))el('openOrderBtn').disabled=!eligible;if(el('orderEligibilityNote'))el('orderEligibilityNote').textContent=eligible?`TOP ${rank} • 100 USDT • sans levier`:'Hors TOP 10 : ticket manuel verrouillé';if(el('trkPerf'))el('trkPerf').textContent=pct(tr.p90);if(el('trkPos'))el('trkPos').textContent=`${tr.posDays.toFixed(2)} %`;if(el('trkVol'))el('trkVol').textContent=`${tr.vol.toFixed(2)} %`;if(el('trkDD'))el('trkDD').textContent=`${tr.dd.toFixed(2)} %`;if(el('trkCont'))el('trkCont').textContent=`${tr.cont.toFixed(2)} %`;if(el('trkScore'))el('trkScore').textContent=`${Math.round(a.ai)}/100`}
function renderUniverse(){const box=el('cryptoRows');if(!box)return;const q=(el('search')?.value||'').trim().toLowerCase(),f=el('statusFilter')?.value||'all';const list=state.rows.filter(a=>(!q||a.name.toLowerCase().includes(q)||a.symbol.toLowerCase().includes(q))&&(f==='all'||a.status===f));box.innerHTML=list.map(a=>`<tr data-unipick="${a.id}"><td>${a.market_cap_rank}</td><td><div class="asset"><img src="${a.image||avatar(a.symbol)}"><div><b>${a.name}</b><small>${a.symbol.toUpperCase()}</small></div></div></td><td>${fmtValue(a.currentPriceUSDT)}</td><td class="${klass(a.price_change_percentage_15m_in_currency)}">${pct(a.price_change_percentage_15m_in_currency)}</td><td class="${klass(a.price_change_percentage_30m_in_currency)}">${pct(a.price_change_percentage_30m_in_currency)}</td><td class="${klass(a.price_change_percentage_1h_in_currency)}">${pct(a.price_change_percentage_1h_in_currency)}</td><td class="${klass(a.price_change_percentage_6h_in_currency)}">${pct(a.price_change_percentage_6h_in_currency)}</td><td class="${klass(a.price_change_percentage_12h_in_currency)}">${pct(a.price_change_percentage_12h_in_currency)}</td><td class="${klass(a.price_change_percentage_24h)}">${pct(a.price_change_percentage_24h)}</td><td class="${klass(a.price_change_percentage_7d_in_currency)}">${pct(a.price_change_percentage_7d_in_currency)}</td><td class="${klass(a.price_change_percentage_30d_in_currency)}">${pct(a.price_change_percentage_30d_in_currency)}</td><td class="${klass(a.price_change_percentage_1y_in_currency)}">${pct(a.price_change_percentage_1y_in_currency)}</td><td>${a.historyYears.toFixed(1)} a</td><td>${fmtCompactUsd(a.total_volume)}</td><td>${score(a.tech)}</td><td>${score(a.quant)}</td><td>${score(a.fund)}</td><td>${score(a.regime)}</td><td>${score(a.fomo)}</td><td>${score(a.mtf)}</td><td>${score(a.ai)}</td><td><span class="side-badge ${chooseSide(a)}">${chooseSide(a).toUpperCase()}</span></td><td><span class="status-pill ${a.status}">${a.label}</span></td></tr>`).join('');$$('[data-unipick]',box).forEach(r=>r.onclick=()=>selectAsset(r.dataset.unipick,true))}
function renderPositions(){const box=el('positionsList');if(!box)return;if(!state.positions.length){box.innerHTML='<div class="empty">Aucune position ouverte. AutoPilot ouvrira des positions uniquement sur données LIVE.</div>';return}const head=`<div class="live-order-head v14"><div>Actif</div><div>Sens</div><div>Mise</div><div>Entrée</div><div>Cours live</div><div>Horizon</div><div>Temps restant</div><div>P&L net live</div><div>Momentum</div><div>Continuation</div><div>Décision IA</div><div>Action</div></div>`;const rows=state.positions.map(p=>{const c=positionCalc(p),a=state.rows.find(x=>x.id===p.assetId),sideAi=a?(p.side==='short'?a.shortAi:a.longAi):num(p.lastAi),opp=a?(p.side==='short'?a.longAi:a.shortAi):0,cont=a?continuationScore(p,a):num(p.lastAi),decision=c.due?'REVUE HORIZON':a&&a.mtf<45&&a.mtfAlignment<45?'MTF EN RUPTURE':sideAi<50&&opp>sideAi+10?'SURVEILLER SORTIE':c.pnlPct>=5&&cont<60?'GAIN À SÉCURISER':c.pnlPct>0?'LAISSER COURIR':'HOLD';return`<div class="live-order-row v14 ${c.net>=0?'profit':'loss'}"><div><div class="live-order-asset"><img src="${p.image||avatar(p.symbol)}"><div><b>${p.name} (${p.symbol.toUpperCase()})</b><small>${p.source} • ${p.broker}</small></div></div></div><div class="live-cell"><span>Sens</span><b><span class="side-badge ${p.side}">${p.side.toUpperCase()}</span></b></div><div class="live-cell"><span>Mise</span><b>100 USDT</b></div><div class="live-cell"><span>Entrée</span><b>${fmtValue(c.entry)}</b></div><div class="live-cell"><span>Live</span><b>${fmtValue(c.cur)}</b></div><div class="live-cell"><span>Horizon</span><b>${horizonLabel(p.horizonMinutes)}</b></div><div class="live-cell"><span>Reste</span><b>${remainingLabel(c.remaining)}</b></div><div class="live-cell"><span>P&L net</span><b class="big ${klass(c.net)}">${fmtValue(c.net)}<br>${pct(c.pnlPct)}</b></div><div class="live-cell"><span>Momentum</span><b>${score(sideAi)}</b></div><div class="live-cell"><span>Continuation</span><b>${score(cont)}</b></div><div><span class="order-status ${decision.includes('SORTIE')||decision.includes('SÉCURISER')?'risk':c.pnlPct>0?'win':''}">${decision}</span></div><div><button class="live-close-btn" data-closepos="${p.id}">CLÔTURER</button></div></div><div class="order-detail-row"><span>Aucun stop fixe</span><span>Aucun TP fixe</span><span>MFE <b class="pos">${pct(p.maxPnlPct)}</b></span><span>MAE <b class="neg">${pct(p.minPnlPct)}</b></span><span>Clôture cible <b>${new Date(p.targetCloseAt).toLocaleString()}</b></span><span>Dernier consensus <b>IA ${score(p.lastAi)} • MTF ${score(p.lastMtf)} • Align ${num(p.lastMtfAlignment).toFixed(0)}% • Risk ${score(p.lastRisk)}</b></span></div>`}).join('');box.innerHTML=head+rows;$$('[data-closepos]',box).forEach(b=>b.onclick=()=>manualClose(b.dataset.closepos))}
function renderDecisions(){const box=el('decisionList');if(!box)return;box.innerHTML=state.decisions.slice(0,30).map(d=>`<div class="decision-row"><span>${new Date(d.at).toLocaleString()}</span><b>#${d.rank} ${d.name} (${d.symbol.toUpperCase()})</b><span class="side-badge ${d.side}">${d.side.toUpperCase()}</span><span>IA ${score(d.ai)}</span><span>FOMO ${score(d.fomo)}</span><span>MTF ${score(d.mtf)}</span><span>Align ${num(d.mtfAlignment).toFixed(0)}%</span><span>Risk ${score(d.risk)}</span><span>${d.decision}</span></div>`).join('')||'<div class="empty">Aucune décision enregistrée.</div>'}
function renderHistory(){const s=accountStats(),box=el('historySummary');if(box){const total=state.closed.length,wins=state.closed.filter(x=>num(x.netPnlUSDT)>0).length,fees=state.closed.reduce((a,x)=>a+num(x.feesUSDT),0);box.innerHTML=[['P&L réalisé',fmtValue(s.realized),`${total} clôturée(s)`],['P&L latent',fmtValue(s.latent),`${state.positions.length} ouverte(s)`],['Capital réalisé',fmtValue(s.realizedCapital),'3 000 + clôturé'],['Capital engagé',fmtValue(s.engaged),'100 × positions'],['Capital disponible',fmtValue(s.available),'réalisé - engagé'],['Equity théorique',fmtValue(s.equity),'réalisé + latent'],['Win rate',`${total?(wins/total*100).toFixed(1):'0.0'} %`,`${wins}/${total}`],['Frais',fmtValue(fees),'cumulés']].map(x=>`<div class="history-stat"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}if(el('historyUpdatedAt'))el('historyUpdatedAt').textContent=`Dernière mise à jour ${new Date().toLocaleString()}`;const list=el('closedList');if(!list)return;if(!state.closed.length){list.innerHTML='<div class="empty">Aucune position clôturée.</div>';return}list.innerHTML=state.closed.map(p=>{const net=num(p.netPnlUSDT),roi=net/100*100;return`<article class="closed-detail-card ${net>=0?'win':'loss'}"><div class="closed-detail-top"><div><b>${p.name} (${p.symbol.toUpperCase()})</b><small>${p.side.toUpperCase()} • 100 USDT • ${p.source}</small></div><div class="${klass(net)}"><strong>${fmtValue(net)}</strong><small>${pct(roi)} sur mise</small></div></div><div class="closed-detail-grid"><span><em>Ouverture</em><b>${new Date(p.openedAt).toLocaleString()}</b></span><span><em>Clôture</em><b>${new Date(p.closedAt).toLocaleString()}</b></span><span><em>Raison</em><b>${p.closeReason}</b></span><span><em>Entrée</em><b>${fmtValue(p.entryPriceUSDT)}</b></span><span><em>Sortie</em><b>${fmtValue(p.exitPriceUSDT)}</b></span><span><em>P&L brut</em><b>${fmtValue(p.grossPnlUSDT)}</b></span><span><em>Frais</em><b>${fmtValue(p.feesUSDT)}</b></span><span><em>P&L net</em><b class="${klass(net)}">${fmtValue(net)}</b></span><span><em>IA/MTF/Align entrée</em><b>${score(p.entryAi)} / ${score(p.entryMtf)} / ${num(p.entryMtfAlignment).toFixed(0)}%</b></span><span><em>FOMO/Risk entrée</em><b>${score(p.entryFomo)} / ${score(p.entryRisk)}</b></span></div></article>`}).join('')}
function safeRender(fn,name){try{fn()}catch(e){console.error(`render ${name}`,e)}}
function renderAll(){safeRender(renderProviderStatus,'providers');safeRender(renderAutoUI,'auto');safeRender(renderKpis,'kpis');safeRender(renderHero,'hero');safeRender(renderTop3,'top3');safeRender(renderCryptoGrid,'top300');safeRender(renderTop10,'top10');safeRender(renderSelected,'selected');safeRender(renderUniverse,'universe');safeRender(renderPositions,'positions');safeRender(renderDecisions,'decisions');safeRender(renderHistory,'history');safeRender(updateNotificationState,'notifications');applyLanguage();renderCountdown()}

function selectAsset(id,scroll=false){const a=state.rows.find(x=>x.id===id)||state.ranked.find(x=>x.id===id);if(!a)return;state.selected=a;renderSelected();renderTop10();renderUniverse();loadChart();if(scroll)document.querySelector('.grid')?.scrollIntoView({behavior:'smooth',block:'start'})}
function openOrder(){const a=state.selected;if(!a)return;if(!state.auth){openAuth();return}if(!state.ranked.slice(0,10).some(x=>x.id===a.id)){toast('Ordre manuel réservé au TOP 10.');return}if(positionByAsset(a.id)){toast('Position déjà ouverte sur cet actif.');return}if(accountStats().available<100||state.positions.length>=15){toast('Capacité du portefeuille atteinte.');return}if(el('modalAsset'))el('modalAsset').textContent=`${a.name} (${a.symbol.toUpperCase()})`;if(el('modalRank'))el('modalRank').textContent=`TOP ${rankOf(a)}`;if(el('capitalInput'))el('capitalInput').value=100;if(el('executionInput'))el('executionInput').value=num(a.currentPriceUSDT).toPrecision(8).replace(/0+$/,'').replace(/\.$/,'');if(el('sideSelect'))el('sideSelect').value=chooseSide(a);if(el('ticketAi'))el('ticketAi').textContent=score(a.ai);if(el('ticketFomo'))el('ticketFomo').textContent=score(a.fomo);if(el('ticketStop'))el('ticketStop').textContent=score(a.risk);if(el('ticketTps'))el('ticketTps').textContent='IA dynamique';if(el('ticketHorizon'))el('ticketHorizon').textContent=`${horizonLabel(horizonMinutes(a))} (IA)`;if(el('ticketFees'))el('ticketFees').textContent=fmtValue(100*CONFIG.feeRoundTripPct/100);if(el('horizonSelect'))el('horizonSelect').value='auto';if(el('manualCheck'))el('manualCheck').checked=false;if(el('confirmOrderBtn'))el('confirmOrderBtn').disabled=true;el('orderModal')?.classList.add('open');el('orderModal')?.setAttribute('aria-hidden','false')}
function closeOrder(){el('orderModal')?.classList.remove('open');el('orderModal')?.setAttribute('aria-hidden','true')}
function confirmOrder(){const a=state.selected;if(!a)return;const raw=el('horizonSelect')?.value||'auto',h=raw==='auto'?horizonMinutes(a):Math.min(Number(raw),CONFIG.maxHorizonMinutes),ok=openPosition(a,{source:'MANUEL',broker:el('brokerSelect')?.value||'MANUEL',side:el('sideSelect')?.value||chooseSide(a),entry:num(el('executionInput')?.value,a.currentPriceUSDT),horizon:h});if(!ok){toast('Ouverture impossible.');return}closeOrder();renderAll();el('positions')?.scrollIntoView({behavior:'smooth'})}
function manualClose(id){const p=state.positions.find(x=>x.id===id);if(!p)return;const c=positionCalc(p);if(!confirm(`Clôturer ${p.symbol.toUpperCase()} maintenant ? P&L net ${fmtValue(c.net)}`))return;closePosition(p,'CLÔTURE MANUELLE',c.cur);renderAll()}

function ensureChart(){if(state.chart||!window.LightweightCharts||!el('chart'))return;try{state.chart=LightweightCharts.createChart(el('chart'),{layout:{background:{type:'solid',color:'#071019'},textColor:'#8ea1af'},grid:{vertLines:{color:'#10202b'},horzLines:{color:'#10202b'}},rightPriceScale:{borderColor:'#1a2a37'},timeScale:{borderColor:'#1a2a37',timeVisible:true}});state.candleSeries=state.chart.addCandlestickSeries({upColor:'#34d399',downColor:'#fb7185',borderUpColor:'#34d399',borderDownColor:'#fb7185',wickUpColor:'#34d399',wickDownColor:'#fb7185'});new ResizeObserver(es=>es.forEach(e=>state.chart.applyOptions({width:e.contentRect.width,height:e.contentRect.height}))).observe(el('chart'))}catch(e){console.warn('chart init',e)}}
function demoCandles(a,days){const count=days===1?48:days===7?84:120,end=Math.floor(Date.now()/1000),step=Math.max(60,Math.floor(days*86400/count)),out=[];let p=num(a.currentPriceUSDT,1);for(let i=count-1;i>=0;i--){const s=(seed(a.id+i)-.5)*.025,o=p,c=o*(1+s),h=Math.max(o,c)*(1+Math.abs(s)*.5+.002),l=Math.min(o,c)*(1-Math.abs(s)*.5-.002);out.push({time:end-i*step,open:o,high:h,low:l,close:c});p=c}return out}
async function loadChart(){const a=state.selected;if(!a)return;ensureChart();if(!state.candleSeries){if(el('chartStatus'))el('chartStatus').textContent='Graphique indisponible';return}if(el('chartStatus'))el('chartStatus').textContent='Chargement des bougies…';let data;try{const j=await fetchMarketData({mode:'klines',symbol:a.symbol,days:String(state.chartDays)},1,10000);data=(j.rows||[]).map(x=>({time:Math.floor(x[0]/1000),open:num(x[1]),high:num(x[2]),low:num(x[3]),close:num(x[4])}));if(!data.length)throw new Error('empty');if(el('chartStatus'))el('chartStatus').textContent=`Bougies • ${j.source||'BINANCE'} LIVE`}catch{data=demoCandles(a,state.chartDays);if(el('chartStatus'))el('chartStatus').textContent='Bougies de secours'}state.candleSeries.setData(data);state.chart.timeScale().fitContent()}
async function refreshPositionPrices(manual=false){if(!state.positions.length){renderKpis();renderPositions();if(manual)toast('Aucune position ouverte.');return}try{const syms=[...new Set(state.positions.map(p=>String(p.symbol||'').toUpperCase()))];const j=await fetchMarketData({mode:'prices',symbols:syms.join(',')},2,9000);let updated=0;for(const p of state.positions){const px=num(j?.prices?.[String(p.symbol||'').toUpperCase()]);const prev=num(p.currentPriceUSDT,p.entryPriceUSDT);if(px>0&&prev>0&&Math.abs(px/prev-1)<.35){p.currentPriceUSDT=px;updated++}const c=positionCalc(p);p.maxPnlPct=Math.max(num(p.maxPnlPct),c.pnlPct);p.minPnlPct=Math.min(num(p.minPnlPct),c.pnlPct)}state.provider.prices=updated===state.positions.length?'LIVE':updated>0?'PARTIEL':'ERREUR';state.provider.priceSource=j?.source||'BINANCE';state.provider.priceError=j?.error||'';state.provider.lastPriceRefresh=Date.now();evaluateExits();persist();renderProviderStatus();renderKpis();renderPositions();renderHistory();if(manual)toast(`${updated}/${state.positions.length} position(s) actualisée(s) • ${state.provider.priceSource}`)}catch(e){state.provider.prices='ERREUR';state.provider.priceError=e?.message||String(e);renderProviderStatus();if(manual)toast('Prix rapides momentanément indisponibles.')}}
function startPriceTimer(){clearInterval(state.priceTimer);state.priceTimer=setInterval(()=>refreshPositionPrices(false),CONFIG.priceMs);refreshPositionPrices(false)}

async function requestNotifications(){if(!('Notification' in window)){toast('Notifications non prises en charge.');return}if(Notification.permission!=='granted')await Notification.requestPermission();updateNotificationState()}
function updateNotificationState(){if(!el('notifyState'))return;const p=('Notification'in window)?Notification.permission:'unsupported';el('notifyState').textContent=p==='granted'?'ON':p==='denied'?'BLOQUÉ':'OFF';el('notifyState').className=`kpi-value compact-value ${p==='granted'?'pos':''}`}
function notifyEvent(title,body){toast(`${title.replace('EBYTDA • ','')} — ${body}`);if('Notification'in window&&Notification.permission==='granted'){try{new Notification(title,{body,icon:'assets/ebyt-da-logo.png'})}catch{}}}
function setUnit(u){state.unit=u==='eur'?'eur':'usdt';persist();$$('[data-unit]').forEach(b=>b.classList.toggle('active',b.dataset.unit===state.unit));renderAll();loadChart()}
function setLang(l){state.lang=l==='en'?'en':'fr';localStorage.setItem('ebyt-v23-lang',state.lang);applyLanguage();renderAll()}
function toggleAuto(){state.autoPilot=!!el('autoPilotToggle')?.checked;persist();renderAutoUI();if(!state.autoPilot){toast('AutoPilot arrêté : pas de nouvelles ouvertures auto.');return}toast('AutoPilot activé : recherche immédiate de positions LIVE.');if(state.liveMarket&&state.ranked.length){runAutoEntries();renderAll()}else if(state.view==='private'){scan(true)}}

function bind(id,event,fn){const x=el(id);if(x)x.addEventListener(event,fn)}
bind('logoHomeBtn','click',showHome);bind('personalSpaceBtn','click',()=>state.auth?showDashboard():openAuth());bind('heroPersonalBtn','click',()=>state.auth?showDashboard():openAuth());bind('securityPersonalBtn','click',()=>state.auth?showDashboard():openAuth());bind('learnMoreBtn','click',()=>el('howItWorks')?.scrollIntoView({behavior:'smooth'}));bind('logoutBtn','click',logout);bind('loginBtn','click',login);$$('[data-close-auth]').forEach(x=>x.onclick=closeAuth);$$('[data-public-nav]').forEach(b=>b.onclick=()=>el(b.dataset.publicNav)?.scrollIntoView({behavior:'smooth'}));$$('[data-private-nav]').forEach(b=>b.onclick=()=>el(b.dataset.privateNav)?.scrollIntoView({behavior:'smooth'}));bind('refreshBtn','click',()=>scan(true));bind('refreshPositionsBtn','click',()=>refreshPositionPrices(true));bind('search','input',renderUniverse);bind('statusFilter','change',renderUniverse);bind('openOrderBtn','click',openOrder);bind('manualCheck','change',e=>{if(el('confirmOrderBtn'))el('confirmOrderBtn').disabled=!e.target.checked});bind('confirmOrderBtn','click',confirmOrder);$$('[data-close-order]').forEach(x=>x.onclick=closeOrder);bind('notifyBtn','click',requestNotifications);bind('autoPilotToggle','change',toggleAuto);$$('[data-lang]').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));$$('[data-unit]').forEach(b=>b.onclick=()=>setUnit(b.dataset.unit));$$('[data-days]').forEach(b=>b.onclick=()=>{$$('[data-days]').forEach(x=>x.classList.toggle('active',x===b));state.chartDays=Number(b.dataset.days);loadChart()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeAuth();closeOrder()}});

sanitizeState();renderProviderStatus();renderAutoUI();applyLanguage();$$('[data-unit]').forEach(b=>b.classList.toggle('active',b.dataset.unit===state.unit));showHome();
})();
