(function(root){
'use strict';
const finite=(n,d=0)=>Number.isFinite(Number(n))?Number(n):d;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function plan(a,fees){const vol=clamp(finite(a.volatilityPricePct,3),1.5,11),stop=clamp(vol*.65,1.5,5),target=10;return{stopPct:stop,targetPct:target,trailPct:clamp(vol*.4,.8,3),horizonMinutes:finite(a.ai)>=85?60:finite(a.ai)>=76?180:720};}
function entry(a,ctx){if(!ctx.fresh)return{ok:false,why:'Données marché périmées'};if(ctx.count>=5)return{ok:false,why:'Cinq positions maximum'};if(ctx.dailyPct<=-3)return{ok:false,why:'Pause : perte quotidienne de 3 %'};const side=a.preferredSide==='short'?'short':'long',p=plan(a,ctx.fees),edge=Math.abs(finite(a.longAi)-finite(a.shortAi));if(!a.mtfFull||!a.mature2y||finite(a.ai)<71||finite(a.risk)<52||finite(a.mtf)<59||finite(a.mtfAlignment)<52||edge<6)return{ok:false,why:'Consensus directionnel insuffisant'};const history=ctx.history.filter(x=>x.side===side&&x.assetId===a.id).slice(0,20);if(history.length>=5&&history.reduce((s,x)=>s+finite(x.netPnlUSDT),0)<0)return{ok:false,why:'Historique net défavorable sur cet actif et ce sens'};return{ok:true,side,plan:p,why:'Consensus MTF confirmé ; objectif net supérieur aux coûts estimés'};}
function exit(p,a,c,now){if(!p.quoteAt||now-p.quoteAt>60000)return{reason:null,status:'Suspendu : prix périmé'};const cfg=p.dayPlan||plan(a||{},.8734),age=(now-new Date(p.openedAt).getTime())/60000;const gross=c.gross/(finite(p.stakeUSDT,100))*100;if(gross<=-cfg.stopPct)return{reason:'STOP VOLATILITÉ',status:'Protection'};if(c.net>=15)return{reason:'TAKE PROFIT +15 USDT NET',status:'Gain verrouillé'};if(age>=2880)return{reason:'HORIZON MAX 48 H',status:'Échéance'};if(age>=1440){const own=a?finite(p.side==='short'?a.shortAi:a.longAi):0,opp=a?finite(p.side==='short'?a.longAi:a.shortAi):100;if(!a||now-finite(p.signalAt)>20*60000||own<70||own-opp<10)return{reason:'24 H — PROLONGATION REFUSÉE',status:'Échéance'};p.extended48h=true;}if(c.pnlPct>=cfg.targetPct)return{reason:'OBJECTIF NET 10 %',status:'Gain'};if(finite(p.maxPnlPct)>=1&&c.pnlPct<=finite(p.maxPnlPct)-cfg.trailPct)return{reason:'TRAILING — PROTECTION DU GAIN',status:'Repli'};if(a&&now-finite(p.signalAt)<=20*60000){const own=finite(p.side==='short'?a.shortAi:a.longAi),opp=finite(p.side==='short'?a.longAi:a.shortAi);if(opp-own>=12&&own<55){if(p.reversalSignalAt!==p.signalAt){p.reversalCount=finite(p.reversalCount)+1;p.reversalSignalAt=p.signalAt;}if(p.reversalCount>=2&&age>=2)return{reason:'RETOURNEMENT CONFIRMÉ SUR DEUX SCANS',status:'Invalidation'};}else{p.reversalCount=0;p.reversalSignalAt=p.signalAt;}if(age>=10&&c.pnlPct>=2&&own<65)return{reason:'GAIN NET — ESSOUFFLEMENT',status:'Gain'};if(age>=cfg.horizonMinutes&&own<60)return{reason:'HORIZON — THÈSE AFFAIBLIE',status:'Échéance'};}return{reason:null,status:'Surveillance du signal et de la volatilité'};}
function day(closed,now,start){const key=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const same=t=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t))===key;const today=closed.filter(p=>same(p.closedAt)),prior=closed.filter(p=>new Date(p.closedAt)<=now&&!same(p.closedAt));const opening=start+prior.reduce((s,p)=>s+finite(p.netPnlUSDT),0),net=today.reduce((s,p)=>s+finite(p.netPnlUSDT),0);return{key,opening,net,pct:opening>0?net/opening*100:0,fees:today.reduce((s,p)=>s+finite(p.feesUSDT),0),long:today.filter(p=>p.side==='long').reduce((s,p)=>s+finite(p.netPnlUSDT),0),short:today.filter(p=>p.side==='short').reduce((s,p)=>s+finite(p.netPnlUSDT),0),count:today.length};}
function dayKey(t){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t));}
function envelope(positions,closed,now){return [...positions,...closed].some(p=>p.banger&&dayKey(p.openedAt)===dayKey(now))?600:500;}
function banger(a,positions,closed,now){return ![...positions,...closed].some(p=>p.banger&&dayKey(p.openedAt)===dayKey(now))&&finite(a.ai)>=90&&finite(a.risk)>=75&&finite(a.mtf)>=80&&finite(a.mtfAlignment)>=80&&Math.abs(finite(a.longAi)-finite(a.shortAi))>=20;}
const api={plan,entry,exit,day,envelope,banger};if(typeof module!=='undefined')module.exports=api;else root.EbytdaDecision=api;
})(typeof globalThis!=='undefined'?globalThis:this);
