[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/logout"
  status = 200

[[redirects]]
  from = "/api/market"
  to = "/.netlify/functions/market"
  status = 200

[[redirects]]
  from = "/api/prices"
  to = "/.netlify/functions/prices"
  status = 200

[[redirects]]
  from = "/api/ai-top3"
  to = "/.netlify/functions/ai-top3"
  status = 200

[[redirects]]
  from = "/api/history"
  to = "/.netlify/functions/history"
  status = 200
