const test=require('node:test'),assert=require('node:assert/strict'),E=require('../decision-engine');
const a={id:'btc',preferredSide:'long',ai:80,risk:70,mtf:80,mtfAlignment:80,longAi:80,shortAi:40,mature2y:true,mtfFull:true,volatilityPricePct:3};
const ctx={fresh:true,count:4,fees:.87,dailyPct:0,history:[]};
test('five slots and fresh directional consensus',()=>{assert(E.entry(a,ctx).ok);assert(!E.entry(a,{...ctx,count:5}).ok);assert(!E.entry(a,{...ctx,fresh:false}).ok);assert(!E.entry({...a,shortAi:79},ctx).ok);assert(!E.entry(a,{...ctx,dailyPct:-3}).ok)});
test('losing track record filters same asset and direction',()=>assert(!E.entry(a,{...ctx,history:Array(5).fill({assetId:'btc',side:'long',netPnlUSDT:-1})}).ok));
const now=Date.now(),base={side:'long',stakeUSDT:100,quoteAt:now,signalAt:now,openedAt:new Date(now-180000),maxPnlPct:0,dayPlan:E.plan(a,.87)};
test('freshness; moderate losses; emergency stop',()=>{assert.equal(E.exit({...base,quoteAt:now-61000},a,{gross:-8,pnlPct:-9},now).reason,null);assert.equal(E.exit({...base},a,{gross:-.5,pnlPct:-1.4},now).reason,null);assert.equal(E.exit({...base},a,{gross:-3,pnlPct:-3.8},now).reason,'STOP VOLATILITÉ')});
test('reversal must use distinct scans, long and short symmetrical',()=>{for(const side of ['long','short']){const p={...base,side};const opposite=side==='long'?{longAi:40,shortAi:85}:{longAi:85,shortAi:40};const c={gross:-.1,pnlPct:-.9};assert.equal(E.exit(p,opposite,c,now).reason,null);assert.equal(E.exit(p,opposite,c,now+15000).reason,null);p.signalAt=now+30000;p.quoteAt=now+30000;assert.equal(E.exit(p,opposite,c,now+30000).reason,'RETOURNEMENT CONFIRMÉ SUR DEUX SCANS')}});
test('profit target, trailing and maximum horizon',()=>{assert.equal(E.exit({...base},a,{gross:12,pnlPct:10,net:10},now).reason,'OBJECTIF NET 10 %');assert.equal(E.exit({...base,maxPnlPct:3},a,{gross:2,pnlPct:1},now).reason,'TRAILING — PROTECTION DU GAIN');assert.equal(E.exit({...base,openedAt:new Date(now-172800001)},a,{gross:0,pnlPct:-.8},now).reason,'HORIZON MAX 48 H')});
test('Paris day boundary, realized net and fees only',()=>{const closed=[{closedAt:'2026-10-04T21:59:00Z',netPnlUSDT:10,feesUSDT:1,side:'long'},{closedAt:'2026-10-04T22:01:00Z',netPnlUSDT:5,feesUSDT:2,side:'short'}];const d=E.day(closed,new Date('2026-10-05T10:00:00Z'),3000);assert.equal(d.opening,3010);assert.equal(d.net,5);assert.equal(d.short,5);assert.equal(d.fees,2);assert.equal(d.count,1)});

test('15 USDT exit overrides continued trend and doubled position',()=>{assert.equal(E.exit({...base,stakeUSDT:200},a,{gross:17,net:15,pnlPct:7.5},now).reason,'TAKE PROFIT +15 USDT NET')});
test('48h extension only on fresh strong directional thesis',()=>{const p={...base,openedAt:new Date(now-86400001)};assert.equal(E.exit(p,a,{gross:-.1,net:-1,pnlPct:-1},now).reason,null);assert(p.extended48h);assert.equal(E.exit({...p},{...a,longAi:55}, {gross:-.1,net:-1,pnlPct:-1},now).reason,'24 H — PROLONGATION REFUSÉE')});
test('one Banger per Paris day persists after close; envelope 600',()=>{const hot={...a,ai:95,risk:80,mtf:90,mtfAlignment:90};assert(E.banger(hot,[],[],now));const used={banger:true,openedAt:new Date(now).toISOString()};assert(!E.banger(hot,[],[used],now));assert.equal(E.envelope([],[used],now),600);assert.equal(E.envelope([],[],now),500)});
